// Erklärungen warum Antwort a) korrekt ist
// Stand: UBI vollständig, SRC/LRC folgen
const EXPLANATIONS = {
// ── UBI I: Binnenschifffahrtsfunk ──────────────────────────────────────────
"UBI-001":'Binnenschifffahrtsfunk ist ein internationaler Dienst – die Regelungen gelten grenzüberschreitend auf Basis der RAINWAT-Vereinbarung (nicht nur national).',
"UBI-002":'Der Binnenschifffahrtsfunk dient dem Funkverkehr für bestimmte Zwecke auf vereinbarten Kanälen (Verkehrskreisen) – Schiffsfunkstellen sind nur eine mögliche Teilnehmergruppe.',
"UBI-003":'Die grundsätzlichen europäischen Regelungen stehen in der Regionalen Vereinbarung RAINWAT (Radiotelephony Agreement for Inland Waterways), nicht im deutschen Landesrecht.',
"UBI-004":'Eine ortsfeste Funkstelle ist eine Landstation (z. B. Revierzentrale, Schleuse) – nicht an Bord eines Schiffes.',
"UBI-005":'Die Revierzentrale ist die zentrale Landfunkstelle des Verkehrskreises Nautische Information und übermittelt Warnungen und Verkehrsinformationen für eine Wasserstraßenregion.',
"UBI-006":'Ein Verkehrsposten ist das niederländische Äquivalent zur deutschen Revierzentrale – eine zentrale ortsfeste Funkstelle der Niederlande.',
"UBI-007":'Der Blockkanal ist in den Niederlanden für sicherheitsrelevante Meldungen der Verkehrsposten und Schiffsfunkstellen reserviert.',
"UBI-008":'MIB steht für „Melde- und Informationssystem in der Binnenschifffahrt" – ein System zur elektronischen Übermittlung von Schiffs- und Reisedaten.',
"UBI-009":'Das UBI gilt in allen Ländern, die der Regionalen Vereinbarung RAINWAT beigetreten sind – nicht nur in EU-Staaten oder deutschsprachigen Ländern.',
"UBI-010":'In den Übergangsbereichen See/Binnenland (Zonen 1 und 2) berechtigt das UBI auch zur Teilnahme am mobilen Seefunkdienst.',
"UBI-011":'Das UBI wird neben dem Bund auch von den Prüfungsausschüssen des DMYV und DSV erteilt, da Sportbootfahrer die Hauptzielgruppe im Binnenbereich sind.',
"UBI-012":'Das UBI berechtigt nur zum Binnenschifffahrtsfunk, nicht zum GMDSS (Global Maritime Distress and Safety System), für das SRC oder LRC erforderlich ist.',
"UBI-013":'Das Amateurfunkzeugnis berechtigt ausschließlich zum Amateurfunk – nicht zur Teilnahme am Binnenschifffahrtsfunk.',
"UBI-014":'Im Ausland gelten die länderspezifischen Regelungen aus den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk, nicht die deutschen Vorschriften.',
"UBI-015":'Die grundsätzlichen Sprechfunkregelungen auf einzelnen Bundeswasserstraßen sind in den Schifffahrtspolizeiverordnungen (z. B. Rheinschifffahrtspolizeiverordnung) geregelt.',
"UBI-016":'Die Ausrüstungspflicht mit Funkanlagen für Binnenschiffe ist in der Binnenschifffahrtsstraßenordnung (BinSchStrO) festgelegt.',
"UBI-017":'Die Funkbenutzungspflicht an bestimmten Stellen oder Strecken findet sich in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk für die jeweilige Wasserstraße.',
"UBI-018":'Abhörverbot und Fernmeldegeheimnis sind im Telekommunikationsgesetz (TKG) geregelt – einem allgemeinen Bundesgesetz für Telekommunikation.',
"UBI-019":'Das Fernmeldegeheimnis schützt Inhalt und alle Umstände des Funkverkehrs, einschließlich der bloßen Tatsache einer Beteiligung – unabhängig vom Inhalt der Nachricht.',
"UBI-020":'Nur Aussendungen „An alle Funkstellen" (z. B. Sicherheitsmeldungen) dürfen uneingeschränkt empfangen und weitergegeben werden – alle anderen unterliegen dem Fernmeldegeheimnis.',
"UBI-021":'Die Verletzung des Fernmeldegeheimnisses ist eine Straftat nach § 206 StGB und kann strafrechtlich verfolgt werden.',
"UBI-022":'Binnenschifffahrtsfunk nutzt den UKW/VHF-Bereich (156–174 MHz), da sich diese Frequenzen gut für die Kommunikation auf Wasserstraßen eignen.',
"UBI-023":'Ultrakurzwellen breiten sich geradlinig (quasioptisch) aus und folgen der Sichtlinie – sie werden nicht an der Ionosphäre reflektiert wie Kurzwellen.',
"UBI-024":'Hindernisse wie Berge oder Hochhäuser können den geradlinigen UKW-Strahl blockieren – Wetter, Tageszeit sowie Kurs und Geschwindigkeit haben keinen relevanten Einfluss.',
// ── UBI II: Funkeinrichtungen & Schiffsfunkstellen ─────────────────────────
"UBI-025":'Eine Schiffsfunkstelle ist die mobile Funkstelle des Binnenschifffahrtsfunks – sie befindet sich an Bord des Schiffes und ist nicht ortsgebunden.',
"UBI-026":'Eine Seefunkstelle ist die Funkstelle des Mobilen Seefunkdienstes an Bord eines nicht dauernd verankerten Seefahrzeuges – sie unterscheidet sich durch den Dienst (Seefunk, nicht Binnenfunk).',
"UBI-027":'Nur Inhaber eines gültigen UBI-Zeugnisses oder eines gleichwertigen Zeugnisses (z. B. SRC/LRC) dürfen eine Schiffsfunkstelle im Binnenschifffahrtsfunk bedienen.',
"UBI-028":'Die Bundesnetzagentur (BNetzA) ist die zuständige Frequenzbehörde in Deutschland und stellt als solche die Zuteilungsurkunde (Ship Station Licence) aus.',
"UBI-029":'Der Betrieb ohne Zuteilungsurkunde (Frequenzzulassung) verstößt gegen das Telekommunikationsgesetz (TKG), das die Frequenznutzung in Deutschland regelt.',
"UBI-030":'Die Bedienung einer Schiffsfunkstelle ohne gültiges Zeugnis verstößt gegen die Binnenschifffahrt-Sprechfunkverordnung (BinSchSprFunkV), die die Zeugnispflicht festlegt.',
"UBI-031":'Die Zuteilungsurkunde (Ship Station Licence) muss als Genehmigungsnachweis für den Betrieb der Funkstelle jederzeit an Bord mitgeführt werden.',
"UBI-032":'Die Bundesnetzagentur (BNetzA) ist als nationale Fernmeldeaufsichtsbehörde für die telekommunikationsrechtliche Überprüfung von Funkstellen zuständig.',
"UBI-033":'Bei Eignerwechsel muss die Bundesnetzagentur (BNetzA) benachrichtigt werden, da die Zuteilungsurkunde (Frequenzzulassung) an den Eigentümer geknüpft ist und neu ausgestellt werden muss.',
"UBI-034":'Technische Änderungen am Gerätebestand müssen der Bundesnetzagentur (BNetzA) gemeldet werden, da sie die bestehende Zuteilungsurkunde betreffen.',
"UBI-035":'Die Bundesnetzagentur (BNetzA) kann als Aufsichtsbehörde den Betrieb einer Schiffsfunkstelle bei Verstößen gegen die Zuteilungsbedingungen untersagen.',
"UBI-036":'Mitgeführt werden müssen der Allgemeine Teil und die Regionalen Teile für alle Strecken, auf denen die Schiffsfunkstelle tatsächlich eingesetzt wird – nicht für alle europäischen Wasserstraßen.',
"UBI-037":'Das Rufzeichen einer deutschen Schiffsfunkstelle besteht aus zwei Buchstaben der deutschen Rufzeichenreihe (DA–DR) gefolgt von vier Ziffern, z. B. DA 5005.',
"UBI-038":'Gültiges Muster: zwei Buchstaben + vier Ziffern (DA 5005). Die anderen Varianten (DABC 55, DA5 0BC, DA 505B) weichen vom vorgeschriebenen Schema ab.',
"UBI-039":'ATIS steht für „Automatisches Senderidentifizierungssystem" – ein Code, der automatisch nach jeder Aussendung gesendet wird, um die Schiffsfunkstelle zu identifizieren.',
"UBI-040":'Der ATIS-Code identifiziert eindeutig die Schiffsfunkstelle – nicht den Bediener, nicht die Seefunkstelle und nicht den Verkehrskreis.',
"UBI-041":'Der ATIS-Code besteht aus 10 Ziffern: zunächst die Ziffer 9, dann die dreistellige Seefunkkennzahl (MID, für Deutschland 211) und schließlich 6 schiffsspezifische Ziffern.',
"UBI-042":'Das ATIS-Signal wird automatisch nach dem Loslassen der Sprechtaste ausgesendet – es schließt jede Aussendung ab und ermöglicht die Identifikation durch andere Stationen.',
"UBI-043":'Tragbare Funkgeräte besitzen keinen eigenen ATIS-Code – sie senden den ATIS-Code der Schiffsfunkstelle, zu der sie gehören.',
"UBI-044":'Der ATIS-Killer ist eine Zusatzeinrichtung, die das empfangene ATIS-Signal akustisch unterdrückt, damit der Datenton am Ende fremder Aussendungen den Empfang nicht stört.',
"UBI-045":'AIS ist das Automatische Schiffsidentifizierungssystem, das auf UKW statische Daten (Name, MMSI), dynamische Daten (Kurs, Geschwindigkeit) und reisebezogene Daten (Ziel) überträgt.',
"UBI-046":'AIS tauscht statische, dynamische und reisebezogene Informationen aus – keine Notfall- oder Alarmdaten, die über DSC oder Sprechfunk übermittelt werden.',
"UBI-047":'Eine Amateurfunkstelle an Bord darf nur mit Zustimmung des Schiffsführers betrieben werden und darf keine Störungen an der Schiffsfunkstelle oder anderen Einrichtungen verursachen.',
"UBI-048":'Das Symbol „=" in technischen Datenblättern steht für Gleichspannung (DC). Das Gerät benötigt also Gleichspannung zwischen 10,8 und 14,6 Volt.',
"UBI-049":'Das Gerät muss für den Binnenschifffahrtsfunk zugelassen oder entsprechend in Verkehr gebracht worden sein – eine allgemeine CE-Kennzeichnung reicht nicht aus.',
"UBI-050":'Je höher die Antenne, desto größer der Sichtbereich und damit die Reichweite – UKW-Wellen breiten sich geradlinig (quasioptisch) aus.',
"UBI-051":'Eine beschädigte Außenisolierung lässt Feuchtigkeit eindringen, was das Antennenkabel dauerhaft beschädigt und die Leistung erheblich mindert. Erneuerung ist sofort erforderlich.',
"UBI-052":'Starkes Rauschen auf allen UKW-Kanälen deutet auf einen Fehler in Antenne oder Antennenkabel hin. Atmosphärische Störungen oder fremde Sender betreffen nicht alle Kanäle gleichmäßig.',
"UBI-053":'Die Ersatzantenne muss für den VHF/UKW-Frequenzbereich des Binnenschifffahrtsfunks (156–174 MHz) ausgelegt sein – Antennen anderer Dienste (z. B. UKW-Radio) passen nicht.',
"UBI-054":'Die Rauschsperre (Squelch) unterdrückt Rauschen und schaltet den Lautsprecher erst ein, wenn ein ausreichend starkes Nutzsignal empfangen wird – schwache Signale werden weiter gedämpft.',
// ── UBI III: Verkehrskreise ────────────────────────────────────────────────
"UBI-055":'Ein Verkehrskreis ordnet bestimmten Zwecken (z. B. Schiff-Schiff, Nautische Information) bestimmte Funkkanäle zu – so ist geordnete Kommunikation ohne Kanalchaos möglich.',
"UBI-056":'Die vier Verkehrskreise sind: Schiff-Schiff, Nautische Information, Schiff-Hafenbehörde und Funkverkehr an Bord. „Schiff-Verkehrszentrale" ist kein Verkehrskreis.',
"UBI-057":'Die Definitionen der Verkehrskreise des Binnenschifffahrtsfunks sind in der Binnenschifffahrt-Sprechfunkverordnung (BinSchSprFunkV) festgelegt.',
"UBI-058":'Nautische Information und Schiff-Hafenbehörde werden nicht auf allen Bundeswasserstraßen angeboten – nur dort, wo entsprechende Landfunkstellen der Behörden vorhanden sind.',
"UBI-059":'Im Verkehrskreis Schiff-Schiff kommunizieren ausschließlich Schiffsfunkstellen untereinander – Landfunkstellen wie Häfen oder Schleusen nehmen hier nicht teil.',
"UBI-060":'Im Verkehrskreis Schiff-Schiff werden nautische Absprachen zwischen Schiffen getroffen: Schutz von Personen, Fahrt und Sicherheit – z. B. Begegnungsabsprachen.',
"UBI-061":'Duisburg Hafen ist eine Landfunkstelle des Verkehrskreises Schiff-Hafenbehörde – Landfunkstellen können am Verkehrskreis Schiff-Schiff nicht teilnehmen.',
"UBI-062":'Die Segelyacht Robbe DA 5005 ist eine Schiffsfunkstelle und darf am Verkehrskreis Schiff-Schiff teilnehmen. Schleuse, Hafen und Revierzentrale sind Landfunkstellen.',
"UBI-063":'Der Verkehrskreis Nautische Information dient dem Funkverkehr zwischen Schiffsfunkstellen und Behörden, denen der Betrieb der Bundeswasserstraßen obliegt (WSV, Schleusen, Revierzentralen).',
"UBI-064":'Im Verkehrskreis Nautische Information werden Wasserstandsmeldungen, Warnungen, Verkehrsberatung und Verkehrslenkung übermittelt – keine Hafendaten oder Bordinformationen.',
"UBI-065":'Eine zusätzliche UKW-Funkanlage kann auf dem NI-Kanal dauerhaft empfangsbereit sein, ohne den übrigen Betrieb zu stören. Dual Watch reicht nicht, da kein gleichzeitiger Empfang möglich ist.',
"UBI-066":'Neuss Hafen ist eine Hafenbehörde und gehört damit zum Verkehrskreis Schiff-Hafenbehörde, nicht zur Nautischen Information.',
"UBI-067":'Iffezheim Schleuse ist eine Behörde, die die Bundeswasserstraße betreibt (WSV), und gehört daher zum Verkehrskreis Nautische Information.',
"UBI-068":'Im Verkehrskreis Schiff-Hafenbehörde kommunizieren Schiffe mit Hafen- und Kaibehörden zu Themen wie Liegeplatzzuweisung und Hafeneinfahrt.',
"UBI-069":'Im Verkehrskreis Schiff-Hafenbehörde werden Informationen über Liegeplätze und die Fahrt in Häfen übermittelt – z. B. wohin anlegen, wann einlaufen.',
"UBI-070":'Düsseldorf Marina ist ein Hafen – die zugehörige Landfunkstelle gehört daher zum Verkehrskreis Schiff-Hafenbehörde.',
"UBI-071":'Gerstheim Ecluse ist eine Schleuse am Rheinseitenkanal (Elsass/Frankreich) und gehört zum Verkehrskreis Nautische Information, nicht zu Schiff-Hafenbehörde.',
"UBI-072":'Duisburg Hafen ist eindeutig eine Hafenbehörde und damit dem Verkehrskreis Schiff-Hafenbehörde zugeordnet. Schleusen und Hebewerke gehören zur Nautischen Information.',
"UBI-073":'Funkverkehr an Bord dient der Kommunikation innerhalb eines Schiffes oder eines Verbandes (z. B. Schubverband) – ausschließlich für schiffsinterne Absprachen.',
"UBI-074":'Im Verkehrskreis Funkverkehr an Bord werden schiffsbetriebliche Nachrichten übermittelt: Leinen, Anker, Manöver – keine externe Kommunikation.',
"UBI-075":'Die Kanäle 15 und 17 sind im Binnenschifffahrtsfunk ausschließlich für den Verkehrskreis Funkverkehr an Bord vorgesehen.',
"UBI-076":'Tragbare Funkanlagen (Handfunkgeräte) dürfen in Deutschland nur im Verkehrskreis Funkverkehr an Bord eingesetzt werden.',
"UBI-077":'Kleinfahrzeuge (Sportboote usw.) dürfen nicht am Verkehrskreis Funkverkehr an Bord teilnehmen – dieser ist der Berufsschifffahrt (Schlepper, Schubschiffe, Fahrgastschiffe) vorbehalten.',
"UBI-078":'In den Verkehrskreisen Schiff-Schiff, Nautische Information und Schiff-Hafenbehörde müssen Schiffsfunkstellen Schiffsname und Rufzeichen als Kennung verwenden.',
"UBI-079":'Schiffsfunkstellen ohne Kleinfahrzeug-Status müssen während der Fahrt in mindestens zwei der Verkehrskreise Schiff-Schiff, Nautische Information oder Schiff-Hafenbehörde empfangsbereit sein.',
"UBI-080":'Die allgemeinen Regelungen zur Abwicklung des Binnenschifffahrtsfunks – für alle Länder gleich – stehen im Allgemeinen Teil des Handbuchs Binnenschifffahrtsfunk.',
// ── UBI IV: Sprechfunk ────────────────────────────────────────────────────
"UBI-081":'Empfohlene fremdsprachliche Redewendungen sind länderspezifisch und stehen daher in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk (nicht im Allgemeinen Teil).',
"UBI-082":'Die internationale Buchstabiertafel (Alpha, Bravo, Charlie …) ermöglicht das eindeutige Übermitteln von Buchstaben bei schlechter Verbindung – um Verwechslungen zu vermeiden.',
"UBI-083":'Welche UKW-Kanäle in welcher Region zu nutzen sind, steht in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk.',
"UBI-084":'Simplex bedeutet Wechselsprechen: immer nur einer sendet. Duplex (Gegensprechen) ermöglicht gleichzeitiges Senden und Empfangen auf zwei Frequenzen.',
"UBI-085":'Im Simplex-Betrieb kann jeder Partner entweder senden oder empfangen – nie beides gleichzeitig. Beim Wechseln von Senden auf Empfangen muss die Sprechtaste losgelassen werden.',
"UBI-086":'Duplex bedeutet Gegensprechen – beide Seiten können gleichzeitig sprechen und hören, wie beim Telefonieren. Dazu werden zwei verschiedene Frequenzen genutzt.',
"UBI-087":'Semi-Duplex ist Wechselsprechen (Sprechtaste drücken zum Senden) auf einem Duplex-Kanal (der technisch zwei Frequenzen nutzt) – z. B. bei Schleusen-Duplexkanälen.',
"UBI-088":'Dual Watch schaltet schnell zwischen zwei Kanälen hin und her, kann aber nicht beide Kanäle gleichzeitig empfangen – es ist daher kein Ersatz für echte Simultanüberwachung.',
"UBI-089":'Auf Kanal 10 (Verkehrskreis Schiff-Schiff) reduziert das Funkgerät die Sendeleistung automatisch, um Störungen auf benachbarten Fahrzeugen zu minimieren.',
"UBI-090":'Auf Kanal 10 wird automatisch auf nur 0,5–1 Watt reduziert (statt bis zu 25 Watt). Die geringe Leistung reicht auf engen Binnenwasserstraßen aus und verhindert Weitreichstörungen.',
"UBI-091":'Kanal 10 ist der Standardkanal für Schiff-Schiff-Kommunikation und muss unabhängig vom Streckenabschnitt ständig überwacht werden.',
"UBI-092":'Kanal 16 ist im Seefunkdienst der internationale UKW-Notruf- und Anrufkanal. Im Binnenschifffahrtsfunk (Zonen 3 und 4) darf er nicht verwendet werden, um Seenotsysteme nicht zu stören.',
"UBI-093":'Die UKW-Kanäle 72 und 77 sind im Binnenschifffahrtsfunk für Nachrichten sozialer Art (private, nicht betriebliche Gespräche) reserviert.',
"UBI-094":'Für Nachrichten sozialer Art (private Gespräche) sind die Kanäle 72 und 77 vorgesehen – Kanäle 15/17 sind für Funkverkehr an Bord, 06/16 für Seefunk.',
"UBI-095":'Gefahrgutschiffe und Sondertransporte unterliegen auf bestimmten Wasserstraßen und an bestimmten Meldepunkten einer Meldepflicht gegenüber den Verkehrsbehörden.',
"UBI-096":'Vor jeder Aussendung muss kurz die Rauschsperre geöffnet werden, um zu prüfen, ob der Kanal frei ist – sonst könnte laufender Funkverkehr gestört werden.',
"UBI-097":'Längere Aussendungen auf Kanal 10 können nicht durch andere Schiffsfunkstellen unterbrochen werden. Daher sollen sie so kurz wie möglich gehalten werden.',
"UBI-098":'Längere Aussendungen auf Kanal 10 können den Empfang des AIS beeinträchtigen, das ebenfalls im UKW-Bereich (161,975 und 162,025 MHz) arbeitet und ständig empfangen werden muss.',
"UBI-099":'Anweisungen einer Revierzentrale oder Schleuse (Verkehrskreis Nautische Information) sind verbindlich und müssen befolgt werden – sie dienen der Verkehrssicherheit.',
"UBI-100":'Schiffsfunkstellen senden auf bestimmten UKW-Kanälen (z. B. Kanal 10) automatisch mit reduzierter Leistung. Das kann die Verbindung zur Seefunkstelle beeinträchtigen, die diese Reduzierung nicht erwartet.',
"UBI-101":'Seefunkanlagen haben keine automatische Leistungsreduzierung auf Binnenfunkkanälen und können keinen ATIS-Code aussenden – beides ist im Binnenschifffahrtsfunk Pflicht.',
"UBI-102":'DSC (Digitaler Selektivruf) ist im Binnenschifffahrtsfunk nicht zulässig – stattdessen wird ATIS zur automatischen Identifizierung der Schiffsfunkstelle eingesetzt.',
"UBI-103":'Bei Verbindungen mit ausländischen Landfunkstellen ist die Sprache des betreffenden Landes zu verwenden, damit Missverständnisse bei Anweisungen (z. B. der Schleuse) vermieden werden.',
"UBI-104":'Testsendungen dürfen 10 Sekunden nicht überschreiten und müssen Rufnamen der Funkstelle sowie das Wort „Test" enthalten, damit andere nicht verwirrt werden.',
"UBI-105":'Meldungen müssen nur auf Verlangen bestätigt werden – eine obligatorische automatische Bestätigung ist nicht vorgeschrieben.',
"UBI-106":'Tafeln an Wasserstraßen und Schleusen weisen den zu benutzenden UKW-Kanal aus (Tafelzeichen mit Aufschrift „UKW XX" oder „VHF XX").',
"UBI-107":'Ein weißes Schild mit rotem Rand (= Gebotsschild) bedeutet: Dieser UKW-Kanal muss benutzt werden – z. B. für die Kommunikation mit einer Schleuse.',
"UBI-108":'Ein blaues Schild mit weißer Aufschrift ist ein Hinweisschild – es weist auf den Nautischen Informationsfunk (NIF) auf dem angegebenen Kanal hin, ohne ein Gebot auszusprechen.',
// ── UBI V: Betriebsverfahren & Rangfolgen ─────────────────────────────────
"UBI-109":'Revierzentralen sind als zentrale Landfunkstellen auf Binnenwasserstraßen die ersten Ansprechpartner zur Einleitung und Koordination von Rettungsmaßnahmen.',
"UBI-110":'Rangfolge: 1. Notverkehr (MAYDAY), 2. Dringlichkeitsverkehr (PAN PAN), 3. Sicherheitsverkehr (SECURITE), 4. Routineverkehr. Höherrangiger Verkehr hat immer Vorrang.',
"UBI-111":'Das Notzeichen im Sprechfunk heißt MAYDAY (von frz. „m\'aidez" = helft mir). Es wird dreimal wiederholt und zeigt unmittelbare Lebensgefahr an.',
"UBI-112":'Notverkehr ist einzuleiten bei unmittelbarer Gefährdung von Mensch oder Schiff ODER wenn Gefahrenabwehr an Land notwendig ist (z. B. drohende Kollision mit Brücke oder Anlage).',
"UBI-113":'Lebensgefährliche Verletzungen bedeuten unmittelbare Gefahr für ein Menschenleben – das erfordert Notverkehr mit MAYDAY.',
"UBI-114":'Person über Bord ist unmittelbare Lebensgefahr – sofort Notverkehr mit MAYDAY einleiten und Rettungsring werfen.',
"UBI-115":'Drohende Kenterung ist unmittelbare Gefahr für Schiff und Besatzung – Notverkehr mit MAYDAY einleiten.',
"UBI-116":'Im Verkehrskreis Nautische Information bestätigt die ortsfeste Funkstelle (Revierzentrale oder Schleuse) die Notmeldung und leitet Rettungsmaßnahmen ein.',
"UBI-117":'Im Verkehrskreis Schiff-Schiff (ohne Landfunkstelle) bestätigt die nächstgelegene Schiffsfunkstelle die Notmeldung und hilft bei der Weitergabe.',
"UBI-118":'MAYDAY RELAY sendet eine Notmeldung im Auftrag einer anderen Stelle – wenn diese selbst nicht mehr senden kann oder die Nachricht nicht weit genug reicht.',
"UBI-119":'SILENCE FINI (frz. „Stille beendet") beendet den Notverkehr und erlaubt allen Funkstellen wieder die normale Kommunikation.',
"UBI-120":'SILENCE MAYDAY gebietet allen nicht am Notverkehr beteiligten Funkstellen Funkstille, damit der Notverkehr nicht gestört wird.',
"UBI-121":'Das Dringlichkeitszeichen lautet PAN PAN (dreimal gesprochen, von frz. „panne" = Panne/Störung). Es steht zwischen MAYDAY (Notfall) und SECURITE (Warnung).',
"UBI-122":'Dringlichkeitsfall liegt vor, wenn dringende Nachrichten über Schiff oder Besatzung übermittelt werden müssen, jedoch keine unmittelbare Lebensgefahr besteht.',
"UBI-123":'Erkrankungen ohne Lebensgefahr oder Schäden ohne unmittelbare Gefahr (z. B. technische Störung ohne Manövrierunfähigkeit) werden mit PAN PAN angekündigt.',
"UBI-124":'Nicht lebensbedrohliche Verletzungen mit Bedarf an baldiger ärztlicher Versorgung sind ein Dringlichkeitsfall (PAN PAN) – kein Notfall (MAYDAY).',
"UBI-125":'Ein Maschinenschaden, der die Sicherheit des Schiffsverkehrs gefährden könnte (z. B. drohende Manövrierunfähigkeit in enger Fahrrinne), ist ein Dringlichkeitsfall (PAN PAN).',
"UBI-126":'Das Sicherheitszeichen lautet SECURITE (frz. Aussprache, dreimal gesprochen). Es kündigt wichtige nautische Warnungen oder Wetterwarnungen an.',
"UBI-127":'Mit SECURITE werden wichtige nautische Warnmeldungen (z. B. Treibgut, Nebel, Pegelstand) oder wichtige Wetterwarnungen angekündigt – kein medizinischer Bezug.',
"UBI-128":'Ein treibender Baumstamm ist eine Gefahr für die Schifffahrt – daher ist eine Sicherheitsmeldung (SECURITE) zu verbreiten.',
"UBI-129":'Eine vertriebene Tonne ist eine falsch positionierte Schifffahrtsmarkierung und damit eine Gefahr – daher ist eine Sicherheitsmeldung (SECURITE) zu verbreiten.',
"UBI-130":'Der Schiffsführer trägt die Gesamtverantwortung für das Schiff und entscheidet daher über die Art der auszusendenden Sprechfunkmeldung.',


// ── SRC I: Grundlagen ─────────────────────────────────────────────────────
"SRC-001":'Mobiler Seefunkdienst verbindet Küsten- und Seefunkstellen miteinander – nicht nur Schiffe untereinander und nicht nur tragbare Geräte.',
"SRC-002":'Das GMDSS ermöglicht schnelle und genaue Alarmierung in Seenotfällen und sichert dadurch die Schifffahrt weltweit.',
"SRC-003":'Das GMDSS wurde für Not-, Dringlichkeits- und Sicherheitsfälle eingeführt – alle drei Kategorien, nicht nur Notfälle.',
"SRC-004":'Die ITU (Internationale Fernmeldeunion) legt die grundlegenden Regelungen für die internationale Telekommunikation fest – keine operative Aufsicht und kein Abrechnungsdienst.',
"SRC-005":'Die VO Funk (Radio Regulations) regelt Frequenzzuweisungen und Betriebsverfahren im Seefunkdienst – nicht Schiffsausrüstung oder Radarnutzung.',
"SRC-006":'Das BSH gibt „Funkdienst für die Klein- und Sportschifffahrt" heraus – die maßgebliche Publikation für Sportseefunker in Deutschland.',
"SRC-007":'Eine Küstenfunkstelle ist eine ortsfeste (landseitige) Funkstelle des mobilen Seefunkdienstes – nicht an Bord eines Schiffes.',
"SRC-008":'Öffentlicher Funkverkehr dient der Allgemeinheit zum Nachrichtenaustausch über öffentliche Netze – er unterliegt dem Fernmeldegeheimnis.',
"SRC-009":'Für öffentlichen Funkverkehr braucht man zusätzlich einen Vertrag mit einer Abrechnungsgesellschaft – das Seefunkzeugnis und die Ship Station Licence sind für alle Seefunkstellen nötig.',
"SRC-010":'Wenn Nachrichten bei einer Küstenfunkstelle vorliegen, erhält die Seefunkstelle eine individuelle Benachrichtigung oder erfährt es durch Abhören von Sammelanrufen.',
"SRC-011":'Seefunkgespräche werden nach Gesprächsdauer und Preis der Verrechnungseinheiten abgerechnet – keine Entfernungsgebühren.',
"SRC-012":'Eine „Sea-Area" im GMDSS ist ein festgelegtes Seegebiet (A1–A4), das die erforderliche Funkausrüstung vorschreibt.',
"SRC-013":'Die GMDSS-Seegebiete heißen A1, A2, A3 und A4 – internationale Bezeichnungen, keine NAVAREA-Einteilung.',
"SRC-014":'Seegebiet A1 ist die Zone, die von einer UKW-Küstenfunkstelle mit kontinuierlichem DSC-Wachdienst abgedeckt wird.',
"SRC-015":'COSPAS-SARSAT und Inmarsat sind die satellitengestützten Alarmierungssysteme im GMDSS – EPIRB ist ein Gerät, das diese Systeme nutzt.',
"SRC-016":'MSI (Maritime Safety Information) sind Nachrichten für die Sicherheit der Seeschifffahrt – Wetterwarnungen, Navigationswarnungen usw.',
"SRC-017":'„WX" ist das Kürzel für Weather (Wetter) – Wetterbericht.',
"SRC-018":'„NX" steht für Navigational (Warning) – nautische Warnnachricht.',
"SRC-019":'AIS ist das Automatische Schiffsidentifizierungssystem, das statische und dynamische Schiffsdaten auf UKW überträgt – nicht das ATIS-System des Binnenfunks.',
"SRC-020":'ETA = Estimated Time of Arrival = voraussichtliche Ankunftszeit.',
"SRC-021":'Im Seefunkdienst gilt die koordinierte Weltzeit UTC – keine Orts- oder Sommerzeit.',
"SRC-022":'LT = Local Time = Ortszeit des Schiffsstandortes – kann von UTC abweichen.',
"SRC-023":'Ein funkärztliches Beratungsgespräch heißt Medico-Gespräch und wird über Küstenfunkstellen abgewickelt.',
// ── SRC II: Funkausrüstung & Zulassung ───────────────────────────────────
"SRC-024":'Eine Seefunkstelle ist eine mobile Funkstelle des Seefunkdienstes an Bord eines nicht dauernd verankerten Seefahrzeuges.',
"SRC-025":'Der Fahrzeugführer muss ein Zeugnis besitzen, das zum Bedienen der eingebauten Anlage berechtigt – bei UKW-Anlage das SRC, bei GW/KW zusätzlich das LRC.',
"SRC-026":'Das SRC berechtigt zum Bedienen von UKW-Funkanlagen auf nicht funkausrüstungspflichtigen Fahrzeugen und Traditionsschiffen.',
"SRC-027":'Gewerbsmäßig genutzte Sportboote ab 12 m Länge müssen mit einer UKW-Seefunkanlage ausgerüstet sein.',
"SRC-028":'Für den Betrieb einer Seefunkstelle benötigt man Ship Station Licence, zugelassenes Gerät und ausreichendes Seefunkzeugnis des Fahrzeugführers.',
"SRC-029":'Bei Überprüfung müssen Ship Station Licence und das Seefunkzeugnis des Fahrzeugführers vorgelegt werden.',
"SRC-030":'In Deutschland stellt die Bundesnetzagentur (BNetzA), Außenstelle Hamburg, die Zuteilungsurkunde für Seefunkstellen aus.',
"SRC-031":'Die Zuteilungsurkunde (Ship Station Licence) muss im Original an Bord mitgeführt werden – keine Kopie.',
"SRC-032":'Namensänderungen müssen der Bundesnetzagentur schriftlich gemeldet werden, damit die Zuteilungsurkunde aktualisiert wird.',
"SRC-033":'Beim Austausch der Funkanlage muss die Bundesnetzagentur schriftlich informiert werden.',
"SRC-034":'Ein UKW-Seefunkgerät muss für den Seefunkdienst zugelassen oder CE-konform in Verkehr gebracht worden sein – kein TÜV-Prüfzeichen nötig.',
"SRC-035":'Funksicherheitszeugnisse für gewerbsmäßig genutzte Sportboote werden von der Dienststelle Schiffssicherheit der BG Verkehr ausgestellt.',
"SRC-036":'Ein Funksicherheitszeugnis ist nur bei gewerbsmäßiger Nutzung eines Sportbootes ab 12 m erforderlich.',
"SRC-037":'Fest installierte UKW-Seefunkanlagen können auf 1 Watt oder maximal 25 Watt umgeschaltet werden.',
"SRC-038":'Sechsstellige Rufzeichen für Seefunkstellen vergibt die Bundesnetzagentur (BNetzA), Außenstelle Hamburg.',
"SRC-039":'Bundesnetzagentur (BNetzA) und BSH sind beide berechtigt, die Funktionsfähigkeit von Seefunkstellen zu überprüfen.',
"SRC-040":'Das mindestens vierstellige Unterscheidungssignal für im Seeschiffsregister eingetragene Yachten teilt das zuständige Amtsgericht zu.',
"SRC-041":'Rufzeichen wie „DDTW" mit vier Buchstaben kennzeichnen Seefunkstellen an Bord in einem deutschen Seeschiffsregister eingetragener Schiffe.',
"SRC-042":'Abhörverbot und Fernmeldegeheimnis sind im Telekommunikationsgesetz (TKG) geregelt.',
"SRC-043":'Zur Wahrung des Fernmeldegeheimnisses verpflichtet sind alle Personen, die eine Seefunkstelle beaufsichtigen, bedienen oder Kenntnis vom Nachrichtenaustausch erlangt haben.',
"SRC-044":'Nur Aussendungen „An alle Funkstellen" dürfen uneingeschränkt aufgenommen und weitergegeben werden.',
"SRC-045":'Ordnungsgemäß in Verkehr gebrachte Funkgeräte tragen das CE-Zeichen.',
"SRC-046":'Zur Teilnahme am Binnenschifffahrtsfunk muss eine spezielle Kombi-Anlage oder eine zusätzliche Anlage für den Binnenschifffahrtsfunk vorhanden sein – eine normale Seefunkanlage reicht nicht.',
"SRC-047":'Kapazität (60 Ah) ÷ Stromaufnahme (0,5 A) = 120 Stunden Betriebsdauer.',
"SRC-048":'Im Sendebetrieb nimmt das Funkgerät deutlich mehr Strom auf als im Empfangsbetrieb – die Batterie wird schneller entladen und die Betriebsdauer verkürzt sich.',
"SRC-049":'Im Empfangsbetrieb nehmen UKW-Seefunkanlagen je nach Gerät zwischen 0,3 und 1 Ampere auf.',
"SRC-050":'Im Sendebetrieb bei 25 Watt liegt die typische Stromaufnahme zwischen 4 und 8 Ampere.',
"SRC-051":'Die Rauschsperre (Squelch) aktiviert den Lautsprecher erst bei ausreichendem Empfangssignalpegel – Rauschen wird unterdrückt.',
"SRC-052":'GPS bestimmt die genaue Position und liefert die genaue Zeit – beides für GMDSS-Funkanlagen wichtig (automatische Positionsübermittlung beim DSC-Notalarm).',
// ── SRC III: DSC ─────────────────────────────────────────────────────────
"SRC-053":'DSC = Digitaler Selektivruf (Digital Selective Calling) – ein digitales Rufverfahren im Seefunkdienst.',
"SRC-054":'Ein DSC ist eine digitale Aussendung, die bei der gerufenen Funkstelle ein optisches und/oder akustisches Signal auslöst – vergleichbar mit einem digitalen Klingelzeichen.',
"SRC-055":'DSC ermöglicht die Verkehrsaufnahme sowohl in Richtung Schiff–Küstenfunkstelle als auch Schiff–Schiff.',
"SRC-056":'DSC-Signale haben eine deutlich größere Reichweite als analoge Sprachaussendungen im gleichen Frequenzbereich.',
"SRC-057":'Für DSC-Ankündigung einer Dringlichkeitsmeldung auf UKW wird Kanal 70 benutzt.',
"SRC-058":'DSC-Alarmierungen auf UKW erfolgen ausschließlich auf Kanal 70.',
"SRC-059":'Eine DSC-ausgerüstete Seefunkstelle wird durch Schiffsname, Rufzeichen und MMSI gekennzeichnet.',
"SRC-060":'Empfangene DSC-Notalarme werden automatisch gespeichert – damit gehen keine Informationen verloren.',
"SRC-061":'MMSI = Maritime Mobile Service Identity = die Rufnummer im Seefunkdienst.',
"SRC-062":'Die Seefunkkennzahlen (MID) für Deutschland sind 211 und 218.',
"SRC-063":'Die eigene MMSI steht in der Zuteilungsurkunde (Ship Station Licence).',
"SRC-064":'Die MMSI besteht aus neun Ziffern, wobei die ersten drei die Seefunkkennzahl (MID) des Landes enthalten.',
"SRC-065":'Die Küstenfunkstellen-MMSI beginnt mit zwei Nullen, gefolgt von der dreistelligen MID und vier weiteren Ziffern.',
"SRC-066":'Die Ziffernfolge 002111240 beginnt mit 00 → Küstenfunkstelle, 211 → Deutschland → deutsche Küstenfunkstelle.',
"SRC-067":'Die Nationalität einer Seefunkstelle ist an den ersten drei Ziffern der MMSI erkennbar – der Seefunkkennzahl (MID).',
"SRC-068":'Nur ein angeschlossener GPS-Empfänger stellt sicher, dass beim DSC-Notalarm automatisch die aktuelle Position übermittelt wird.',
// ── SRC IV: Technik & Frequenzen ─────────────────────────────────────────
"SRC-069":'30–300 MHz ist der Bereich der Ultrakurzwellen (UKW / VHF = Very High Frequency).',
"SRC-070":'Das SRC (Short Range Certificate / Beschränkt Gültiges Funkbetriebszeugnis) ist das Mindestzeugnis für GMDSS auf UKW.',
"SRC-071":'Das SRC berechtigt zum mobilen Seefunkdienst auf UKW/VHF – nicht auf GW/KW und nicht für Satellit.',
"SRC-072":'Duplex = Gegensprechen auf zwei Frequenzen – beide Seiten können gleichzeitig senden und empfangen.',
"SRC-073":'Simplex = Wechselsprechen auf einer Frequenz – immer nur einer sendet.',
"SRC-074":'Semi-Duplex = Wechselsprechen auf zwei Frequenzen – man drückt die Sprechtaste zum Senden, nutzt aber einen Duplex-Kanal.',
"SRC-075":'Die UKW-Kanäle 06, 08, 72 und 77 sind international ausschließlich für Schiff-Schiff-Verkehr vorgesehen.',
"SRC-076":'Die UKW-Kanäle 75 und 76 dürfen ausschließlich für navigationsrelevanten Funkverkehr genutzt werden.',
"SRC-077":'Atmosphärische Störungen sind im VHF-Bereich kein relevantes Problem – anders als auf Mittelwelle oder Kurzwelle.',
"SRC-078":'UKW-Wellen breiten sich geradlinig (quasioptisch) aus – sie folgen der Sichtlinie und werden nicht an der Ionosphäre reflektiert.',
"SRC-079":'Die internationalen UKW-Seefunkkanäle reichen von Kanal 1 bis 28 und 60 bis 88.',
"SRC-080":'Die Reichweite einer UKW-Anlage hängt hauptsächlich von der Antennenhöhe ab – je höher, desto weiter der Horizont.',
"SRC-081":'UKW-Antennen müssen vertikal ausgerichtet sein, da die Funkwellen vertikal polarisiert sind.',
"SRC-082":'Metallische Gegenstände in der Nähe der Antenne beeinträchtigen die Abstrahlung am stärksten.',
"SRC-083":'Schlechtes Wetter hat keinen Einfluss auf die Reichweite eines UKW-Handsprechfunkgerätes – im Gegensatz zu Antennenhöhe, Akkuladung und Sendeleistung.',
"SRC-084":'Ob das Senden in ausländischen Häfen gestattet ist, hängt von den Vorschriften des jeweiligen Landes ab.',
// ── SRC V: Betriebsverfahren ──────────────────────────────────────────────
"SRC-085":'Rangfolge im Seefunkdienst: 1. Not, 2. Dringlichkeit, 3. Sicherheit, 4. Routine.',
"SRC-086":'Im Schiffstagebuch sind Not-, Dringlichkeits- und Sicherheitsverkehr sowie wichtige Vorkommnisse zu dokumentieren.',
"SRC-087":'Funkverkehr zwischen Küstenfunkstellen des Revier-/Hafenfunkdienstes und Seefunkstellen ist nichtöffentlicher Funkverkehr.',
"SRC-088":'Der Revier- und Hafenfunkdienst übermittelt Nachrichten, die ausschließlich das Führen, die Fahrt und Sicherheit von Schiffen auf dem Revier oder in Häfen betreffen.',
"SRC-089":'Der Schiffslenkungsfunkdienst ist neben dem Revier- und Hafenfunkdienst der zweite Sicherheitsfunkdienst im mobilen Seefunkdienst.',
"SRC-090":'Bei einer Verbindung zwischen See- und Küstenfunkstelle bestimmt die Küstenfunkstelle den Arbeitskanal.',
"SRC-091":'Küstenfunkstellen des Revier- und Hafenfunkdienstes werden nach dem Muster „Geografischer Name + Art des Dienstes + Radio" bezeichnet, z. B. „Warnemünde Traffic".',
"SRC-092":'„Warnemünde Traffic" ist der Rufname der Küstenfunkstelle des Revierfunkdienstes in Warnemünde.',
"SRC-093":'Das Dringlichkeitszeichen zeigt an, dass eine sehr dringende Meldung folgt, welche die Sicherheit einer mobilen Einheit oder Person betrifft – jedoch keine unmittelbare Lebensgefahr.',
"SRC-094":'Das Dringlichkeitszeichen im Sprechfunk lautet PAN PAN (dreimal gesprochen).',
"SRC-095":'PAN PAN kündigt eine Dringlichkeitsmeldung an.',
"SRC-096":'Eine Dringlichkeitsmeldung auf UKW wird per DSC auf Kanal 70 angekündigt und dann per Sprechfunk auf Kanal 16 ausgesendet.',
"SRC-097":'„URGENCY" im DSC-Controller zeigt an, dass die folgende Meldung dringend ist und die Sicherheit einer mobilen Einheit oder Person betrifft.',
"SRC-098":'Dringlichkeitsmeldungen können an alle Funkstellen oder an eine bestimmte Funkstelle gerichtet werden.',
"SRC-099":'Eine an alle Funkstellen gesendete Dringlichkeitsmeldung muss durch eine Meldung an alle Funkstellen aufgehoben werden.',
"SRC-100":'Das Sicherheitszeichen im Seefunkdienst lautet SECURITE (dreimal gesprochen).',
"SRC-101":'Mit SECURITE wird eine Sicherheitsmeldung eingeleitet.',
"SRC-102":'Eine Sicherheitsmeldung enthält eine wichtige nautische Warnnachricht oder eine wichtige Wetterwarnung.',
"SRC-103":'Sportfahrzeuge benutzen in deutschen Hoheitsgewässern vorzugsweise Kanal 69 oder 72 für den Schiff-Schiff-Verkehr.',
"SRC-104":'UKW-Handsprechfunkgeräte werden vorzugsweise für Funkverkehr an Bord und für die Verbindung mit Überlebensfahrzeugen eingesetzt.',
"SRC-105":'Testsendungen dürfen 10 Sekunden nicht überschreiten und müssen das Wort „Test" sowie eine Schiffskennung enthalten.',
"SRC-106":'Der Schiff-Schiff-Verkehr auf UKW erfolgt im Wechselsprechen (Simplex) auf einer Frequenz.',
"SRC-107":'Kanal 70 ist ausschließlich für den Digitalen Selektivruf (DSC) reserviert – keine Sprachaussendungen.',
"SRC-108":'Kanal 16 dient für Not-, Dringlichkeitsverkehr, Ankündigung von Sicherheitsmeldungen und als allgemeiner Anrufkanal.',
"SRC-109":'Mit GMDSS-Seefunkanlage muss auf Kanal 70 (DSC-Wachkanal) empfangsbereit sein – nicht auf Kanal 16.',
"SRC-110":'Ohne GMDSS-Anlage (reine Sprechfunkanlage) muss auf Kanal 16 abgehört werden.',
"SRC-111":'Kanal 06 ist der bevorzugte Kanal für Schiff-Schiff-Verkehr und koordinierte SAR-Einsätze.',
"SRC-112":'Anrufkanal dient der Verbindungsaufnahme, Arbeitskanal der eigentlichen Abwicklung des Funkverkehrs.',
"SRC-113":'Küstenfunkstellen mit DSC werden auf Kanal 70 oder dem veröffentlichten Arbeitskanal gerufen – nicht auf Kanal 16.',
"SRC-114":'Küstenfunkstellen ohne DSC werden direkt auf dem Arbeitskanal gerufen.',
"SRC-115":'Vor dem Anruf auf einem Arbeitskanal muss geprüft werden, ob laufender Funkverkehr gestört werden würde.',
// ── SRC VI: NAVTEX ───────────────────────────────────────────────────────
"SRC-116":'NAVTEX = Nautische Warnnachrichten im Funktelexverfahren (Navigational Telex) auf Mittelwelle.',
"SRC-117":'NAVTEX ist der terrestrische Dienst zur Verbreitung von MSI (Maritime Safety Information).',
"SRC-118":'Auf 518 kHz (englisch) und 490 kHz (Landessprache) bieten DWD und BSH gemeinsam den deutschen NAVTEX-Dienst an.',
"SRC-119":'NAVTEX-Meldungen können auf ca. 600 Seemeilen vom Sender empfangen werden.',
"SRC-120":'Beim NAVTEX-Empfänger müssen die gewünschten Sender und die Art der benötigten Meldungen eingestellt werden.',
"SRC-121":'Navigationswarnungen, meteorologische Warnungen und SAR-Meldungen können im NAVTEX nicht unterdrückt werden – sie sind sicherheitsrelevant.',
"SRC-122":'Auf 490 kHz werden NAVTEX-Nachrichten in der Landessprache der Sendestelle ausgestrahlt.',
"SRC-123":'Deutsche NAVTEX-Sender senden alle 4 Stunden reguläre Informationen aus.',
"SRC-124":'Eine NAVAREA ist ein international festgelegtes Vorhersage- und Seewarngebiet – eines von 21 NAVAREA-Gebieten weltweit.',
// ── SRC VII: Not- und Sicherheitsverkehr ─────────────────────────────────
"SRC-125":'SAR = Search and Rescue = Suche und Rettung.',
"SRC-126":'Ein RCC (Rescue Co-ordination Centre) koordiniert die im Seenotfall zur Verfügung stehenden Kräfte und den Notverkehr.',
"SRC-127":'Ein MRCC (Maritime Rescue Co-ordination Centre) koordiniert alle SAR-Maßnahmen auf See.',
"SRC-128":'„On-Scene Communication" ist der Funkverkehr vor Ort im Seenotfall zwischen Havarist und Helfern.',
"SRC-129":'Der On-Scene Coordinator (OSC) leitet die Such- und Rettungsmaßnahmen direkt vor Ort.',
"SRC-130":'Funkverkehr vor Ort ist der Funkverkehr zwischen dem Schiff in Not, den helfenden Fahrzeugen und dem koordinierenden Fahrzeug.',
"SRC-131":'Nur der Fahrzeugführer ist berechtigt, das Aussenden einer Notmeldung zu veranlassen.',
"SRC-132":'Mit DSC ausgerüstete Schiffe müssen auf Kanal 70 empfangsbereit sein – der DSC-Wachkanal im GMDSS.',
"SRC-133":'Das Notzeichen im Sprechfunk lautet MAYDAY (dreimal gesprochen, von frz. „m\'aidez" = helft mir).',
"SRC-134":'Der Notverkehr im Sprechfunk wird mit MAYDAY eingeleitet – nicht mit dem Schiffsnamen oder SOS.',
"SRC-135":'Ein Seenotfall liegt vor, wenn ein Schiff oder eine Person von einer ernsten und unmittelbaren Gefahr bedroht ist und sofortige Hilfe benötigt.',
"SRC-136":'Bei Lebensgefahr wird die Alarmierungspriorität „Notfall" gewählt.',
"SRC-137":'Im Notfall darf jede verfügbare und geeignete Frequenz genutzt werden – nicht nur die Notfrequenzen.',
"SRC-138":'Notverkehr findet vorzugsweise auf Kanal 16 statt.',
"SRC-139":'Auf Kanal 16 dürfen Notmeldungen, Dringlichkeitsmeldungen und Ankündigungen von Sicherheitsmeldungen übermittelt werden.',
"SRC-140":'Die Einleitung des Notverkehrs wird wiederholt, wenn keine Antwort erfolgt oder der Fahrzeugführer es für notwendig hält.',
"SRC-141":'Den Notalarm für ein anderes Schiff richtet man grundsätzlich an die nächstgelegene Küstenfunkstelle oder an alle Funkstellen.',
"SRC-142":'Eine Seefunkstelle bestätigt einen DSC-Notalarm nur, wenn sie tatsächlich Hilfe leisten kann.',
"SRC-143":'Die Bestätigung darf erst nach Bestätigung durch eine Küstenfunkstelle oder nach angemessener Wartefrist erfolgen, um zu vermeiden, dass alle gleichzeitig antworten.',
"SRC-144":'Ein auf Kanal 70 empfangener Notalarm wird auf Kanal 16 im Sprechfunkverfahren bestätigt.',
"SRC-145":'SILENCE MAYDAY fordert alle nicht am Notverkehr beteiligten Funkstellen zur Funkstille auf.',
"SRC-146":'SILENCE MAYDAY wird von der Funkstelle ausgesendet, die den Notverkehr leitet.',
"SRC-147":'Nach Eingang eines Notalarms übernimmt das MRCC die Koordinierung und Information zu den SAR-Maßnahmen.',
"SRC-148":'Bremen Rescue Radio ist auf Kanal 16 (Sprechfunk) und Kanal 70 (DSC) empfangsbereit.',
"SRC-149":'Im Notfall mit SAR-Hubschraubern gilt das Betriebsverfahren des mobilen Seefunkdienstes.',
"SRC-150":'Das Handbuch „Suche und Rettung" enthält internationale Redewendungen, Abkürzungen und Verfahren für Notfälle.',
"SRC-151":'SAR-Einheiten arbeiten im UKW-Bereich – auf Kanal 16 und Kanal 06.',
"SRC-152":'Im Funkverkehr zwischen Seefunkstellen und SAR-Hubschraubern gilt das Betriebsverfahren des Seefunkdienstes.',
"SRC-153":'Für den Funkverkehr mit SAR-Hubschraubern werden vorzugsweise Kanal 16 und Kanal 06 benutzt.',
"SRC-154":'Bei SAR-Hubschraubereinsätzen werden Kanal 16 und 06 durch Zweikanal-Überwachung (Dual Watch) gleichzeitig überwacht.',
"SRC-155":'Ein Schiff in Not soll Kanal 16 abhören, bis der SAR-Hubschrauber ankommt.',
"SRC-156":'Während eines Notverkehrs auf Kanal 16 darf eine Dringlichkeitsmeldung per DSC auf Kanal 70 angekündigt und dann auf einem Schiff-Schiff-Kanal ausgesendet werden.',
"SRC-157":'Bei irrtümlichem Notalarm: Gerät zurücksetzen, Fehlalarm per DSC zurücknehmen und per Sprechfunk auf Kanal 16 „An alle Funkstellen" zurücknehmen.',
"SRC-158":'Ein UKW-Empfänger (ohne Senderfunktion) kann keine SAR-Maßnahmen auslösen oder erleichtern – er kann nur empfangen.',
"SRC-159":'SART und EPIRB werden zur Ortsbestimmung eingesetzt: SART via Radar, EPIRB via Satellit (COSPAS-SARSAT).',
"SRC-160":'Eine EPIRB soll im äußeren Decksbereich installiert werden, damit sie bei einem Untergang des Schiffes automatisch aufschwimmt und auslöst.',
"SRC-161":'Eine EPIRB darf nur im echten Notfall aktiviert werden – Testsendungen über das Satellitensystem sind nicht zulässig.',
"SRC-162":'Eine EPIRB kann im Notfall manuell oder automatisch (durch Wasserdruckauslöser) aktiviert werden.',
"SRC-163":'EPIRBs werden im Seenotfall automatisch durch den Wasserdruckauslöser aktiviert, wenn sie ins Wasser eintauchen.',
"SRC-164":'Eine EPIRB sendet Notsignal, Identifikationsmerkmal und – wenn GPS vorhanden – die Position.',
"SRC-165":'In den Seegebieten A1–A3 läuft der EPIRB-Alarm dank geostationärer Satelliten innerhalb weniger Minuten im MRCC auf.',
"SRC-166":'Ohne GPS-Positionsdaten kann es bei COSPAS-SARSAT (LEOSAR) bis zu 4 Stunden dauern, bis die Position ermittelt ist.',
"SRC-167":'Die Positionsermittlung dauert länger, wenn keine GPS-Daten vorhanden sind, weil Überflüge der umlaufenden LEOSAR-Satelliten abgewartet werden müssen.',
"SRC-168":'Die maximale Positionsabweichung einer COSPAS-SARSAT-EPIRB ohne GPS beträgt 2 Seemeilen.',
"SRC-169":'121,5 MHz dient zur Zielfahrt (Homing) für SAR-Kräfte vor Ort, 406 MHz zur Alarmierung und Positionsbestimmung über Satelliten.',
"SRC-170":'An einer EPIRB müssen Schiffsname/Rufzeichen/MMSI, Seriennummer, Batteriehaltbarkeitsdatum und Datum des Wasserdruckauslösers erkennbar sein.',
"SRC-171":'Vor der Wartung muss sichergestellt sein, dass kein Fehlalarm ausgelöst wird, wenn die EPIRB aus der Halterung entfernt wird.',
"SRC-172":'An der EPIRB sind regelmäßig Batteriehaltbarkeitsdatum, Haltbarkeitsdatum des Wasserdruckauslösers und die Funktion entsprechend Herstellerangaben zu prüfen.',
"SRC-173":'Ein aktivierter SART erscheint auf dem Radarbildschirm als Linie von mindestens zwölf Punkten/Zeichen.',
"SRC-174":'Das SART-Signal wird von einem Radargerät empfangen und angezeigt – kein GPS oder DSC.',
"SRC-175":'Eine UKW-Seefunkanlage alarmiert alle in Funkreichweite befindlichen Seefunkstellen gleichzeitig – ein Mobiltelefon kann nur einzelne Nummern anrufen.',
"SRC-176":'Die UKW-Seefunkanlage erreicht alle in Funkreichweite befindlichen Fahrzeuge gleichzeitig – das Mobiltelefon kann nur einen Gesprächspartner erreichen.',
"SRC-177":'Telefongespräche sind Einzelverbindungen – andere Fahrzeuge können nicht mithören, sodass wichtige Rettungsinformationen nicht allen Beteiligten zur Verfügung stehen.',
"SRC-178":'Der Notverkehr wird mit einer Meldung beendet, die mit SILENCE FINI abschließt.',
"SRC-179":'Ein SART sendet Ortungsfunksignale, die von Radargeräten auf einem Schirm als Linie von Punkten dargestellt werden.',
"SRC-180":'Eine EPIRB alarmiert und kennzeichnet die Notposition über das COSPAS-SARSAT-Satellitensystem.',

// ── LRC I: Satellitenfunk Grundlagen ─────────────────────────────────────
"LRC-001":'Im Satellitenfunk heißt die mobile Schiffsanlage Mobile Earth Station (MES) – also Schiffs-Erdfunkstelle.',
"LRC-002":'Eine Schiffs-Erdfunkstelle ist die mobile Erdfunkstelle des Satelliten-Seefunkdienstes an Bord eines Schiffes.',
"LRC-003":'Eine Land-Erdfunkstelle (LES = Land Earth Station) ist die ortsfeste landseitige Gegenstelle im Satellitenfunknetz.',
"LRC-004":'Der Azimutwinkel ist der horizontale Winkel vom Meridian des Schiffes zum Satelliten – die „Kompesspeilung" des Satelliten.',
"LRC-005":'Der Elevationswinkel (elevation angle) ist der Winkel zwischen Horizont und Satellit vom Schiff aus – gibt an, wie hoch der Satellit am Himmel steht.',
"LRC-006":'Die ITU-Region 1 umfasst Europa und Afrika.',
"LRC-007":'A3 ist das Seegebiet innerhalb der Überdeckung eines geostationären Inmarsat-Satelliten mit ununterbrochener DSC-Alarmierungsbereitschaft.',
"LRC-008":'A4 umfasst die Polgebiete – Gewässer nördlich von ca. 70° Nord und südlich von ca. 70° Süd – die von geostationären Satelliten nicht abgedeckt werden.',
"LRC-009":'Inmarsat-Satelliten sind geostationär und können die Polgebiete (A4) nicht abdecken – nur polumlaufende Satelliten (COSPAS-SARSAT) erreichen diese Gebiete.',
"LRC-010":'AMVER (Automated Mutual-Assistance Vessel Rescue System) ist das Positionsmeldesystem für Such- und Rettungszwecke.',
"LRC-011":'AIS arbeitet im UKW-Bereich (VHF) auf den Kanälen 87B und 88B (161,975 MHz und 162,025 MHz).',
"LRC-012":'Die NAVTEX-Kurzwellenfrequenz ist 4209,5 kHz.',
"LRC-013":'Im Seenotfall kann ein Alarm über Satelliten über die Schiffs-Erdfunkstelle (SES) oder eine Satelliten-Seenotfunkbake (EPIRB) ausgelöst werden.',
"LRC-014":'COSPAS-SARSAT nutzt sowohl polumlaufende (LEOSAR) als auch geostationäre (GEOSAR) Satelliten – Inmarsat ist rein geostationär.',
// ── LRC II: LRC-Zeugnis ───────────────────────────────────────────────────
"LRC-015":'Im Seegebiet A3 (Inmarsat-Abdeckung) ist das LRC (Long Range Certificate / Allgemeines Funkbetriebszeugnis) das Mindestzeugnis.',
"LRC-016":'Das LRC berechtigt zum mobilen Seefunkdienst und zum mobilen Seefunkdienst über Satelliten.',
"LRC-017":'Mit dem LRC dürfen Seefunkanlagen im UKW-, GW- und KW-Bereich sowie über Satellit auf Sportfahrzeugen und Traditionsschiffen bedient werden.',
"LRC-018":'Für den Betrieb einer KW/GW-DSC-Anlage ist das LRC (Allgemeines Funkbetriebszeugnis) erforderlich.',
// ── LRC III: GW- und KW-Frequenzen ───────────────────────────────────────
"LRC-019":'2177 kHz ist die nationale und internationale Routineanruffrequenz für Schiff-Schiff-DSC auf Grenzwelle.',
"LRC-020":'2177,0 kHz ist die Antwortfrequenz der Küstenfunkstelle auf Routineanrufe per DSC.',
"LRC-021":'2189,5 kHz ist die internationale DSC-Anruffrequenz für Routineanrufe an Küstenfunkstellen auf Grenzwelle.',
"LRC-022":'Für DSC im Kurzwellenbereich werden die Frequenzbereiche 4, 6, 8, 12 und 16 MHz genutzt.',
"LRC-023":'Die Bestätigung eines auf 2187,5 kHz (DSC-Notruffrequenz GW) empfangenen Notalarms erfolgt auf 2182,0 kHz im Sprechfunkverfahren.',
"LRC-024":'Im KW-Bereich gewährleistet ein Wachempfänger im Scan-Betrieb die Empfangsbereitschaft auf mehreren Frequenzen gleichzeitig.',
// ── LRC IV: Wellenausbreitung ────────────────────────────────────────────
"LRC-025":'Grenzwelle (GW/MF) umfasst 1605–4000 kHz.',
"LRC-026":'SSB mit unterdrücktem Träger wird als J3E bezeichnet – die effizienteste Sendeart für Weitverkehr.',
"LRC-027":'Grenzwelle (GW/MF) reicht für mindestens 150 Seemeilen Reichweite bei Tagbetrieb aus – UKW nicht.',
"LRC-028":'Im LW- und tagsüber im MW/GW-Bereich spielt die Bodenwelle die entscheidende Rolle bei der Ausbreitung.',
"LRC-029":'Im Seegebiet A2 (ca. 150 sm von der Küste) sind GW für die Küstenfunkstelle und UKW für nahe Seefunkstellen geeignet.',
"LRC-030":'Gewitter verursachen auf Mittelwelle (NAVTEX 518/490 kHz) starke atmosphärische Störungen bis zur vollständigen Unlesbarkeit.',
"LRC-031":'Kurzwelle (KW/HF) wird für den Weitverkehr im terrestrischen Seefunkdienst genutzt – Raumwellenausbreitung über weite Strecken.',
"LRC-032":'Kurzwelle (KW/HF) umfasst den allgemeinen Bereich von 3–30 MHz.',
"LRC-033":'Im Kurzwellenbereich (KW/HF) spielt die Raumwelle die entscheidende Rolle – sie wird an der Ionosphäre reflektiert.',
"LRC-034":'Die „Tote Zone" (Skip Zone) tritt im Kurzwellenbereich auf – zwischen dem Ende der Bodenwelle und dem ersten Raumwelleneinfall gibt es keinen Empfang.',
"LRC-035":'Gegen Mitternacht ist die Ionosphäre stärker ionisiert – für die gleiche Entfernung wird ein niedrigerer Frequenzbereich benötigt.',
"LRC-036":'Kurzwellenverbindungen sind durch tageszeitliche, jahreszeitliche und solare Schwankungen der Ionosphäre nicht zuverlässig vorherzuplanen.',
"LRC-037":'Für Weitverkehr auf KW sollte die Antenne die Energie möglichst flach abstrahlen, damit die Raumwelle mit wenigen Ionosphärensprüngen den Zielort erreicht.',
"LRC-038":'Für die Strecke Mittelmeer nach Norddeutschland ist tagsüber der 8-MHz-Bereich (Kurzwelle) typischerweise am besten geeignet.',
"LRC-039":'In den Abendstunden ist für die Verbindung Karibik–USA der 6-MHz-Bereich auf Kurzwelle oft am geeignetsten, da die Ionosphäre sich nach Sonnenuntergang abschwächt.',
"LRC-040":'Auf 100 sm Entfernung ist Grenzwelle (GW/MF) die geeignetste Option – sie überbrückt zuverlässig kurze bis mittlere Entfernungen.',
// ── LRC V: GW/KW-Betriebsverfahren ───────────────────────────────────────
"LRC-041":'Bei Verbindungen zwischen See- und Küstenfunkstelle bestimmt die Küstenfunkstelle die zu benutzende Arbeitsfrequenz.',
"LRC-042":'Das „Verzeichnis der Küstenfunkstellen" (List of Coast Stations) der ITU enthält Angaben zu Arbeitsfrequenzen von Küstenfunkstellen.',
"LRC-043":'In deutschen Häfen dürfen UKW (VHF), UHF und der 1,6-GHz-Bereich (Inmarsat) genutzt werden – KW/GW sind in Häfen verboten.',
"LRC-044":'„ITU-Channel 1604" bedeutet Kanal 04 im 16-MHz-Seefunkband – die erste Zahl ist das Frequenzband in MHz.',
"LRC-045":'2182,0 kHz ist die internationale Not- und Sicherheitsfrequenz für Sprechfunk auf Grenzwelle.',
"LRC-046":'Für die Dringlichkeitsmeldung „An alle Funkstellen" auf GW wird nach DSC-Ankündigung auf 2187,5 kHz der Sprechfunk auf 2182,0 kHz verwendet.',
"LRC-047":'Während eines Notverkehrs auf 2182 kHz wird eine Dringlichkeitsmeldung zunächst per DSC auf 2187,5 kHz angekündigt und dann auf einer Schiff-Schiff-Frequenz ausgesendet.',
"LRC-048":'Eine Sicherheitsmeldung auf GW wird per DSC auf 2187,5 kHz angekündigt und dann per Sprechfunk auf einer GW-Schiff-Schiff-Arbeitsfrequenz ausgesendet.',
"LRC-049":'Notverkehr im KW-Sprechfunkverfahren wird auf der Sprechfunk-Notfrequenz des KW-Bandes abgewickelt, in dem der Notalarm ausgesendet wurde.',
"LRC-050":'Im GW- und KW-Bereich wird für Sprachaussendungen Einseitenband mit unterdrücktem Träger (SSB, J3E) verwendet – energieeffizienter als AM.',
// ── LRC VI: Inmarsat ──────────────────────────────────────────────────────
"LRC-051":'Das Inmarsat-Handbuch enthält Angaben über die Abdeckungsbereiche der Inmarsat-Satelliten.',
"LRC-052":'Das Inmarsat-Handbuch enthält auch Angaben über Land-Erdfunkstellen (LES).',
"LRC-053":'Der PSA (Point of Service Activation) schaltet die Schiffs-Erdfunkstelle für den Inmarsat-Dienst frei.',
"LRC-054":'Die NCS (Network Co-ordination Station) vergibt automatisch die Arbeitskanäle an LES und MES im Inmarsat-Netz.',
"LRC-055":'Inmarsat-Satelliten sind geostationär – sie stehen immer über demselben Punkt des Äquators.',
"LRC-056":'Geostationäre Satelliten befinden sich über 0° Breite (Äquator) in etwa 35.786 km Höhe.',
"LRC-057":'AOR-E = Atlantic Ocean Region East – deckt den östlichen Atlantik einschließlich Europa ab.',
"LRC-058":'IOR = Indian Ocean Region – deckt den Indischen Ozean ab.',
"LRC-059":'POR = Pacific Ocean Region – deckt den Pazifischen Ozean ab.',
"LRC-060":'Von Hawaii aus ist der POR-Satellit (Pazifik) am besten erreichbar für eine Verbindung nach Europa.',
"LRC-061":'Von den Malediven (Indischer Ozean) bietet der IOR-Satellit die beste Verbindung nach Europa.',
"LRC-062":'Seegebiet A4 (Polargebiete) liegt außerhalb der Abdeckung geostationärer Inmarsat-Satelliten.',
"LRC-063":'Seegebiet A2 ist das Gebiet innerhalb der Sprechfunkreichweite einer GW-Küstenfunkstelle mit ununterbrochener DSC-Bereitschaft.',
"LRC-064":'Die Vorwahl +870 wird für Verbindungen zu Inmarsat-Terminals (Schiffs-Erdfunkstellen) verwendet.',
"LRC-065":'Inmarsat-C-Rufnummern beginnen mit der Ziffer 4.',
"LRC-066":'Rufnummern, die mit 4 beginnen, gehören zu Inmarsat C.',
"LRC-067":'Inmarsat C bietet Telex, Datenübertragung und Telefax in Richtung See–Land – keine Telefonie.',
"LRC-068":'Die Funktionsfähigkeit einer Inmarsat-C-Anlage lässt sich prüfen, indem man eine Nachricht von der eigenen an die eigene Anlage schickt (Loopback-Test).',
"LRC-069":'Vor dem Ausschalten einer Inmarsat-C-Anlage muss man sich ordnungsgemäß ausloggen, damit das System die Verbindung sauber beendet.',
"LRC-070":'Für Anrufe von Land an bestimmte Schiffs-Erdfunkstellen wird der Erweiterte Gruppenanruf (EGC) verwendet.',
"LRC-071":'EGC (Enhanced Group Call) wird vom SafetyNet-Dienst für Sicherheitsinformationen über Satelliten genutzt.',
"LRC-072":'Über EGC werden maritime Sicherheitsinformationen (MSI) oder Informationen an bestimmte Empfängergruppen ausgesendet.',
"LRC-073":'Für den Empfang von EGC-Meldungen wird ein Satelliten-Empfänger (Inmarsat-C-Gerät) benötigt.',
"LRC-074":'Über Inmarsat ausgelöste Notalarme werden umgehend an das zuständige RCC oder MRCC weitergeleitet.',
"LRC-075":'SafetyNet ist der Inmarsat-Dienst, der maritime Sicherheitsinformationen (MSI) über Satellit verbreitet.',
"LRC-076":'SafetyNet verbreitet Maritime Safety Information (MSI) – Navigationswarnungen, Wetterwarnungen usw. – über Satelliten.',
};
