// Erklärungen warum Antwort a) korrekt ist
// Stand: UBI vollständig, SRC/LRC folgen
const EXPLANATIONS = {
// ── UBI I: Binnenschifffahrtsfunk ──────────────────────────────────────────
1077:'Binnenschifffahrtsfunk ist ein internationaler Dienst – die Regelungen gelten grenzüberschreitend auf Basis der RAINWAT-Vereinbarung (nicht nur national).',
1078:'Der Binnenschifffahrtsfunk dient dem Funkverkehr für bestimmte Zwecke auf vereinbarten Kanälen (Verkehrskreisen) – Schiffsfunkstellen sind nur eine mögliche Teilnehmergruppe.',
1079:'Die grundsätzlichen europäischen Regelungen stehen in der Regionalen Vereinbarung RAINWAT (Radiotelephony Agreement for Inland Waterways), nicht im deutschen Landesrecht.',
1080:'Eine ortsfeste Funkstelle ist eine Landstation (z. B. Revierzentrale, Schleuse) – nicht an Bord eines Schiffes.',
1081:'Die Revierzentrale ist die zentrale Landfunkstelle des Verkehrskreises Nautische Information und übermittelt Warnungen und Verkehrsinformationen für eine Wasserstraßenregion.',
1082:'Ein Verkehrsposten ist das niederländische Äquivalent zur deutschen Revierzentrale – eine zentrale ortsfeste Funkstelle der Niederlande.',
1083:'Der Blockkanal ist in den Niederlanden für sicherheitsrelevante Meldungen der Verkehrsposten und Schiffsfunkstellen reserviert.',
1084:'MIB steht für „Melde- und Informationssystem in der Binnenschifffahrt" – ein System zur elektronischen Übermittlung von Schiffs- und Reisedaten.',
1085:'Das UBI gilt in allen Ländern, die der Regionalen Vereinbarung RAINWAT beigetreten sind – nicht nur in EU-Staaten oder deutschsprachigen Ländern.',
1086:'In den Übergangsbereichen See/Binnenland (Zonen 1 und 2) berechtigt das UBI auch zur Teilnahme am mobilen Seefunkdienst.',
1087:'Das UBI wird neben dem Bund auch von den Prüfungsausschüssen des DMYV und DSV erteilt, da Sportbootfahrer die Hauptzielgruppe im Binnenbereich sind.',
1088:'Das UBI berechtigt nur zum Binnenschifffahrtsfunk, nicht zum GMDSS (Global Maritime Distress and Safety System), für das SRC oder LRC erforderlich ist.',
1089:'Das Amateurfunkzeugnis berechtigt ausschließlich zum Amateurfunk – nicht zur Teilnahme am Binnenschifffahrtsfunk.',
1090:'Im Ausland gelten die länderspezifischen Regelungen aus den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk, nicht die deutschen Vorschriften.',
1091:'Die grundsätzlichen Sprechfunkregelungen auf einzelnen Bundeswasserstraßen sind in den Schifffahrtspolizeiverordnungen (z. B. Rheinschifffahrtspolizeiverordnung) geregelt.',
1092:'Die Ausrüstungspflicht mit Funkanlagen für Binnenschiffe ist in der Binnenschifffahrtsstraßenordnung (BinSchStrO) festgelegt.',
1093:'Die Funkbenutzungspflicht an bestimmten Stellen oder Strecken findet sich in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk für die jeweilige Wasserstraße.',
1094:'Abhörverbot und Fernmeldegeheimnis sind im Telekommunikationsgesetz (TKG) geregelt – einem allgemeinen Bundesgesetz für Telekommunikation.',
1095:'Das Fernmeldegeheimnis schützt Inhalt und alle Umstände des Funkverkehrs, einschließlich der bloßen Tatsache einer Beteiligung – unabhängig vom Inhalt der Nachricht.',
1096:'Nur Aussendungen „An alle Funkstellen" (z. B. Sicherheitsmeldungen) dürfen uneingeschränkt empfangen und weitergegeben werden – alle anderen unterliegen dem Fernmeldegeheimnis.',
1097:'Die Verletzung des Fernmeldegeheimnisses ist eine Straftat nach § 206 StGB und kann strafrechtlich verfolgt werden.',
1098:'Binnenschifffahrtsfunk nutzt den UKW/VHF-Bereich (156–174 MHz), da sich diese Frequenzen gut für die Kommunikation auf Wasserstraßen eignen.',
1099:'Ultrakurzwellen breiten sich geradlinig (quasioptisch) aus und folgen der Sichtlinie – sie werden nicht an der Ionosphäre reflektiert wie Kurzwellen.',
1100:'Hindernisse wie Berge oder Hochhäuser können den geradlinigen UKW-Strahl blockieren – Wetter, Tageszeit sowie Kurs und Geschwindigkeit haben keinen relevanten Einfluss.',
// ── UBI II: Funkeinrichtungen & Schiffsfunkstellen ─────────────────────────
1101:'Eine Schiffsfunkstelle ist die mobile Funkstelle des Binnenschifffahrtsfunks – sie befindet sich an Bord des Schiffes und ist nicht ortsgebunden.',
1102:'Eine Seefunkstelle ist die Funkstelle des Mobilen Seefunkdienstes an Bord eines nicht dauernd verankerten Seefahrzeuges – sie unterscheidet sich durch den Dienst (Seefunk, nicht Binnenfunk).',
1103:'Nur Inhaber eines gültigen UBI-Zeugnisses oder eines gleichwertigen Zeugnisses (z. B. SRC/LRC) dürfen eine Schiffsfunkstelle im Binnenschifffahrtsfunk bedienen.',
1104:'Die Bundesnetzagentur (BNetzA) ist die zuständige Frequenzbehörde in Deutschland und stellt als solche die Zuteilungsurkunde (Ship Station Licence) aus.',
1105:'Der Betrieb ohne Zuteilungsurkunde (Frequenzzulassung) verstößt gegen das Telekommunikationsgesetz (TKG), das die Frequenznutzung in Deutschland regelt.',
1106:'Die Bedienung einer Schiffsfunkstelle ohne gültiges Zeugnis verstößt gegen die Binnenschifffahrt-Sprechfunkverordnung (BinSchSprFunkV), die die Zeugnispflicht festlegt.',
1107:'Die Zuteilungsurkunde (Ship Station Licence) muss als Genehmigungsnachweis für den Betrieb der Funkstelle jederzeit an Bord mitgeführt werden.',
1108:'Die Bundesnetzagentur (BNetzA) ist als nationale Fernmeldeaufsichtsbehörde für die telekommunikationsrechtliche Überprüfung von Funkstellen zuständig.',
1109:'Bei Eignerwechsel muss die Bundesnetzagentur (BNetzA) benachrichtigt werden, da die Zuteilungsurkunde (Frequenzzulassung) an den Eigentümer geknüpft ist und neu ausgestellt werden muss.',
1110:'Technische Änderungen am Gerätebestand müssen der Bundesnetzagentur (BNetzA) gemeldet werden, da sie die bestehende Zuteilungsurkunde betreffen.',
1111:'Die Bundesnetzagentur (BNetzA) kann als Aufsichtsbehörde den Betrieb einer Schiffsfunkstelle bei Verstößen gegen die Zuteilungsbedingungen untersagen.',
1112:'Mitgeführt werden müssen der Allgemeine Teil und die Regionalen Teile für alle Strecken, auf denen die Schiffsfunkstelle tatsächlich eingesetzt wird – nicht für alle europäischen Wasserstraßen.',
1113:'Das Rufzeichen einer deutschen Schiffsfunkstelle besteht aus zwei Buchstaben der deutschen Rufzeichenreihe (DA–DR) gefolgt von vier Ziffern, z. B. DA 5005.',
1114:'Gültiges Muster: zwei Buchstaben + vier Ziffern (DA 5005). Die anderen Varianten (DABC 55, DA5 0BC, DA 505B) weichen vom vorgeschriebenen Schema ab.',
1115:'ATIS steht für „Automatisches Senderidentifizierungssystem" – ein Code, der automatisch nach jeder Aussendung gesendet wird, um die Schiffsfunkstelle zu identifizieren.',
1116:'Der ATIS-Code identifiziert eindeutig die Schiffsfunkstelle – nicht den Bediener, nicht die Seefunkstelle und nicht den Verkehrskreis.',
1117:'Der ATIS-Code besteht aus 10 Ziffern: zunächst die Ziffer 9, dann die dreistellige Seefunkkennzahl (MID, für Deutschland 211) und schließlich 6 schiffsspezifische Ziffern.',
1118:'Das ATIS-Signal wird automatisch nach dem Loslassen der Sprechtaste ausgesendet – es schließt jede Aussendung ab und ermöglicht die Identifikation durch andere Stationen.',
1119:'Tragbare Funkgeräte besitzen keinen eigenen ATIS-Code – sie senden den ATIS-Code der Schiffsfunkstelle, zu der sie gehören.',
1120:'Der ATIS-Killer ist eine Zusatzeinrichtung, die das empfangene ATIS-Signal akustisch unterdrückt, damit der Datenton am Ende fremder Aussendungen den Empfang nicht stört.',
1121:'AIS ist das Automatische Schiffsidentifizierungssystem, das auf UKW statische Daten (Name, MMSI), dynamische Daten (Kurs, Geschwindigkeit) und reisebezogene Daten (Ziel) überträgt.',
1122:'AIS tauscht statische, dynamische und reisebezogene Informationen aus – keine Notfall- oder Alarmdaten, die über DSC oder Sprechfunk übermittelt werden.',
1123:'Eine Amateurfunkstelle an Bord darf nur mit Zustimmung des Schiffsführers betrieben werden und darf keine Störungen an der Schiffsfunkstelle oder anderen Einrichtungen verursachen.',
1124:'Das Symbol „=" in technischen Datenblättern steht für Gleichspannung (DC). Das Gerät benötigt also Gleichspannung zwischen 10,8 und 14,6 Volt.',
1125:'Das Gerät muss für den Binnenschifffahrtsfunk zugelassen oder entsprechend in Verkehr gebracht worden sein – eine allgemeine CE-Kennzeichnung reicht nicht aus.',
1126:'Je höher die Antenne, desto größer der Sichtbereich und damit die Reichweite – UKW-Wellen breiten sich geradlinig (quasioptisch) aus.',
1127:'Eine beschädigte Außenisolierung lässt Feuchtigkeit eindringen, was das Antennenkabel dauerhaft beschädigt und die Leistung erheblich mindert. Erneuerung ist sofort erforderlich.',
1128:'Starkes Rauschen auf allen UKW-Kanälen deutet auf einen Fehler in Antenne oder Antennenkabel hin. Atmosphärische Störungen oder fremde Sender betreffen nicht alle Kanäle gleichmäßig.',
1129:'Die Ersatzantenne muss für den VHF/UKW-Frequenzbereich des Binnenschifffahrtsfunks (156–174 MHz) ausgelegt sein – Antennen anderer Dienste (z. B. UKW-Radio) passen nicht.',
1130:'Die Rauschsperre (Squelch) unterdrückt Rauschen und schaltet den Lautsprecher erst ein, wenn ein ausreichend starkes Nutzsignal empfangen wird – schwache Signale werden weiter gedämpft.',
// ── UBI III: Verkehrskreise ────────────────────────────────────────────────
1131:'Ein Verkehrskreis ordnet bestimmten Zwecken (z. B. Schiff-Schiff, Nautische Information) bestimmte Funkkanäle zu – so ist geordnete Kommunikation ohne Kanalchaos möglich.',
1132:'Die vier Verkehrskreise sind: Schiff-Schiff, Nautische Information, Schiff-Hafenbehörde und Funkverkehr an Bord. „Schiff-Verkehrszentrale" ist kein Verkehrskreis.',
1133:'Die Definitionen der Verkehrskreise des Binnenschifffahrtsfunks sind in der Binnenschifffahrt-Sprechfunkverordnung (BinSchSprFunkV) festgelegt.',
1134:'Nautische Information und Schiff-Hafenbehörde werden nicht auf allen Bundeswasserstraßen angeboten – nur dort, wo entsprechende Landfunkstellen der Behörden vorhanden sind.',
1135:'Im Verkehrskreis Schiff-Schiff kommunizieren ausschließlich Schiffsfunkstellen untereinander – Landfunkstellen wie Häfen oder Schleusen nehmen hier nicht teil.',
1136:'Im Verkehrskreis Schiff-Schiff werden nautische Absprachen zwischen Schiffen getroffen: Schutz von Personen, Fahrt und Sicherheit – z. B. Begegnungsabsprachen.',
1137:'Duisburg Hafen ist eine Landfunkstelle des Verkehrskreises Schiff-Hafenbehörde – Landfunkstellen können am Verkehrskreis Schiff-Schiff nicht teilnehmen.',
1138:'Die Segelyacht Robbe DA 5005 ist eine Schiffsfunkstelle und darf am Verkehrskreis Schiff-Schiff teilnehmen. Schleuse, Hafen und Revierzentrale sind Landfunkstellen.',
1139:'Der Verkehrskreis Nautische Information dient dem Funkverkehr zwischen Schiffsfunkstellen und Behörden, denen der Betrieb der Bundeswasserstraßen obliegt (WSV, Schleusen, Revierzentralen).',
1140:'Im Verkehrskreis Nautische Information werden Wasserstandsmeldungen, Warnungen, Verkehrsberatung und Verkehrslenkung übermittelt – keine Hafendaten oder Bordinformationen.',
1141:'Eine zusätzliche UKW-Funkanlage kann auf dem NI-Kanal dauerhaft empfangsbereit sein, ohne den übrigen Betrieb zu stören. Dual Watch reicht nicht, da kein gleichzeitiger Empfang möglich ist.',
1142:'Neuss Hafen ist eine Hafenbehörde und gehört damit zum Verkehrskreis Schiff-Hafenbehörde, nicht zur Nautischen Information.',
1143:'Iffezheim Schleuse ist eine Behörde, die die Bundeswasserstraße betreibt (WSV), und gehört daher zum Verkehrskreis Nautische Information.',
1144:'Im Verkehrskreis Schiff-Hafenbehörde kommunizieren Schiffe mit Hafen- und Kaibehörden zu Themen wie Liegeplatzzuweisung und Hafeneinfahrt.',
1145:'Im Verkehrskreis Schiff-Hafenbehörde werden Informationen über Liegeplätze und die Fahrt in Häfen übermittelt – z. B. wohin anlegen, wann einlaufen.',
1146:'Düsseldorf Marina ist ein Hafen – die zugehörige Landfunkstelle gehört daher zum Verkehrskreis Schiff-Hafenbehörde.',
1147:'Gerstheim Ecluse ist eine Schleuse am Rheinseitenkanal (Elsass/Frankreich) und gehört zum Verkehrskreis Nautische Information, nicht zu Schiff-Hafenbehörde.',
1148:'Duisburg Hafen ist eindeutig eine Hafenbehörde und damit dem Verkehrskreis Schiff-Hafenbehörde zugeordnet. Schleusen und Hebewerke gehören zur Nautischen Information.',
1149:'Funkverkehr an Bord dient der Kommunikation innerhalb eines Schiffes oder eines Verbandes (z. B. Schubverband) – ausschließlich für schiffsinterne Absprachen.',
1150:'Im Verkehrskreis Funkverkehr an Bord werden schiffsbetriebliche Nachrichten übermittelt: Leinen, Anker, Manöver – keine externe Kommunikation.',
1151:'Die Kanäle 15 und 17 sind im Binnenschifffahrtsfunk ausschließlich für den Verkehrskreis Funkverkehr an Bord vorgesehen.',
1152:'Tragbare Funkanlagen (Handfunkgeräte) dürfen in Deutschland nur im Verkehrskreis Funkverkehr an Bord eingesetzt werden.',
1153:'Kleinfahrzeuge (Sportboote usw.) dürfen nicht am Verkehrskreis Funkverkehr an Bord teilnehmen – dieser ist der Berufsschifffahrt (Schlepper, Schubschiffe, Fahrgastschiffe) vorbehalten.',
1154:'In den Verkehrskreisen Schiff-Schiff, Nautische Information und Schiff-Hafenbehörde müssen Schiffsfunkstellen Schiffsname und Rufzeichen als Kennung verwenden.',
1155:'Schiffsfunkstellen ohne Kleinfahrzeug-Status müssen während der Fahrt in mindestens zwei der Verkehrskreise Schiff-Schiff, Nautische Information oder Schiff-Hafenbehörde empfangsbereit sein.',
1156:'Die allgemeinen Regelungen zur Abwicklung des Binnenschifffahrtsfunks – für alle Länder gleich – stehen im Allgemeinen Teil des Handbuchs Binnenschifffahrtsfunk.',
// ── UBI IV: Sprechfunk ────────────────────────────────────────────────────
1157:'Empfohlene fremdsprachliche Redewendungen sind länderspezifisch und stehen daher in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk (nicht im Allgemeinen Teil).',
1158:'Die internationale Buchstabiertafel (Alpha, Bravo, Charlie …) ermöglicht das eindeutige Übermitteln von Buchstaben bei schlechter Verbindung – um Verwechslungen zu vermeiden.',
1159:'Welche UKW-Kanäle in welcher Region zu nutzen sind, steht in den Regionalen Teilen des Handbuchs Binnenschifffahrtsfunk.',
1160:'Simplex bedeutet Wechselsprechen: immer nur einer sendet. Duplex (Gegensprechen) ermöglicht gleichzeitiges Senden und Empfangen auf zwei Frequenzen.',
1161:'Im Simplex-Betrieb kann jeder Partner entweder senden oder empfangen – nie beides gleichzeitig. Beim Wechseln von Senden auf Empfangen muss die Sprechtaste losgelassen werden.',
1162:'Duplex bedeutet Gegensprechen – beide Seiten können gleichzeitig sprechen und hören, wie beim Telefonieren. Dazu werden zwei verschiedene Frequenzen genutzt.',
1163:'Semi-Duplex ist Wechselsprechen (Sprechtaste drücken zum Senden) auf einem Duplex-Kanal (der technisch zwei Frequenzen nutzt) – z. B. bei Schleusen-Duplexkanälen.',
1164:'Dual Watch schaltet schnell zwischen zwei Kanälen hin und her, kann aber nicht beide Kanäle gleichzeitig empfangen – es ist daher kein Ersatz für echte Simultanüberwachung.',
1165:'Auf Kanal 10 (Verkehrskreis Schiff-Schiff) reduziert das Funkgerät die Sendeleistung automatisch, um Störungen auf benachbarten Fahrzeugen zu minimieren.',
1166:'Auf Kanal 10 wird automatisch auf nur 0,5–1 Watt reduziert (statt bis zu 25 Watt). Die geringe Leistung reicht auf engen Binnenwasserstraßen aus und verhindert Weitreichstörungen.',
1167:'Kanal 10 ist der Standardkanal für Schiff-Schiff-Kommunikation und muss unabhängig vom Streckenabschnitt ständig überwacht werden.',
1168:'Kanal 16 ist im Seefunkdienst der internationale UKW-Notruf- und Anrufkanal. Im Binnenschifffahrtsfunk (Zonen 3 und 4) darf er nicht verwendet werden, um Seenotsysteme nicht zu stören.',
1169:'Die UKW-Kanäle 72 und 77 sind im Binnenschifffahrtsfunk für Nachrichten sozialer Art (private, nicht betriebliche Gespräche) reserviert.',
1170:'Für Nachrichten sozialer Art (private Gespräche) sind die Kanäle 72 und 77 vorgesehen – Kanäle 15/17 sind für Funkverkehr an Bord, 06/16 für Seefunk.',
1171:'Gefahrgutschiffe und Sondertransporte unterliegen auf bestimmten Wasserstraßen und an bestimmten Meldepunkten einer Meldepflicht gegenüber den Verkehrsbehörden.',
1172:'Vor jeder Aussendung muss kurz die Rauschsperre geöffnet werden, um zu prüfen, ob der Kanal frei ist – sonst könnte laufender Funkverkehr gestört werden.',
1173:'Längere Aussendungen auf Kanal 10 können nicht durch andere Schiffsfunkstellen unterbrochen werden. Daher sollen sie so kurz wie möglich gehalten werden.',
1174:'Längere Aussendungen auf Kanal 10 können den Empfang des AIS beeinträchtigen, das ebenfalls im UKW-Bereich (161,975 und 162,025 MHz) arbeitet und ständig empfangen werden muss.',
1175:'Anweisungen einer Revierzentrale oder Schleuse (Verkehrskreis Nautische Information) sind verbindlich und müssen befolgt werden – sie dienen der Verkehrssicherheit.',
1176:'Schiffsfunkstellen senden auf bestimmten UKW-Kanälen (z. B. Kanal 10) automatisch mit reduzierter Leistung. Das kann die Verbindung zur Seefunkstelle beeinträchtigen, die diese Reduzierung nicht erwartet.',
1177:'Seefunkanlagen haben keine automatische Leistungsreduzierung auf Binnenfunkkanälen und können keinen ATIS-Code aussenden – beides ist im Binnenschifffahrtsfunk Pflicht.',
1178:'DSC (Digitaler Selektivruf) ist im Binnenschifffahrtsfunk nicht zulässig – stattdessen wird ATIS zur automatischen Identifizierung der Schiffsfunkstelle eingesetzt.',
1179:'Bei Verbindungen mit ausländischen Landfunkstellen ist die Sprache des betreffenden Landes zu verwenden, damit Missverständnisse bei Anweisungen (z. B. der Schleuse) vermieden werden.',
1180:'Testsendungen dürfen 10 Sekunden nicht überschreiten und müssen Rufnamen der Funkstelle sowie das Wort „Test" enthalten, damit andere nicht verwirrt werden.',
1181:'Meldungen müssen nur auf Verlangen bestätigt werden – eine obligatorische automatische Bestätigung ist nicht vorgeschrieben.',
1182:'Tafeln an Wasserstraßen und Schleusen weisen den zu benutzenden UKW-Kanal aus (Tafelzeichen mit Aufschrift „UKW XX" oder „VHF XX").',
1183:'Ein weißes Schild mit rotem Rand (= Gebotsschild) bedeutet: Dieser UKW-Kanal muss benutzt werden – z. B. für die Kommunikation mit einer Schleuse.',
1184:'Ein blaues Schild mit weißer Aufschrift ist ein Hinweisschild – es weist auf den Nautischen Informationsfunk (NIF) auf dem angegebenen Kanal hin, ohne ein Gebot auszusprechen.',
// ── UBI V: Betriebsverfahren & Rangfolgen ─────────────────────────────────
1185:'Revierzentralen sind als zentrale Landfunkstellen auf Binnenwasserstraßen die ersten Ansprechpartner zur Einleitung und Koordination von Rettungsmaßnahmen.',
1186:'Rangfolge: 1. Notverkehr (MAYDAY), 2. Dringlichkeitsverkehr (PAN PAN), 3. Sicherheitsverkehr (SECURITE), 4. Routineverkehr. Höherrangiger Verkehr hat immer Vorrang.',
1187:'Das Notzeichen im Sprechfunk heißt MAYDAY (von frz. „m\'aidez" = helft mir). Es wird dreimal wiederholt und zeigt unmittelbare Lebensgefahr an.',
1188:'Notverkehr ist einzuleiten bei unmittelbarer Gefährdung von Mensch oder Schiff ODER wenn Gefahrenabwehr an Land notwendig ist (z. B. drohende Kollision mit Brücke oder Anlage).',
1189:'Lebensgefährliche Verletzungen bedeuten unmittelbare Gefahr für ein Menschenleben – das erfordert Notverkehr mit MAYDAY.',
1190:'Person über Bord ist unmittelbare Lebensgefahr – sofort Notverkehr mit MAYDAY einleiten und Rettungsring werfen.',
1191:'Drohende Kenterung ist unmittelbare Gefahr für Schiff und Besatzung – Notverkehr mit MAYDAY einleiten.',
1192:'Im Verkehrskreis Nautische Information bestätigt die ortsfeste Funkstelle (Revierzentrale oder Schleuse) die Notmeldung und leitet Rettungsmaßnahmen ein.',
1193:'Im Verkehrskreis Schiff-Schiff (ohne Landfunkstelle) bestätigt die nächstgelegene Schiffsfunkstelle die Notmeldung und hilft bei der Weitergabe.',
1194:'MAYDAY RELAY sendet eine Notmeldung im Auftrag einer anderen Stelle – wenn diese selbst nicht mehr senden kann oder die Nachricht nicht weit genug reicht.',
1195:'SILENCE FINI (frz. „Stille beendet") beendet den Notverkehr und erlaubt allen Funkstellen wieder die normale Kommunikation.',
1196:'SILENCE MAYDAY gebietet allen nicht am Notverkehr beteiligten Funkstellen Funkstille, damit der Notverkehr nicht gestört wird.',
1197:'Das Dringlichkeitszeichen lautet PAN PAN (dreimal gesprochen, von frz. „panne" = Panne/Störung). Es steht zwischen MAYDAY (Notfall) und SECURITE (Warnung).',
1198:'Dringlichkeitsfall liegt vor, wenn dringende Nachrichten über Schiff oder Besatzung übermittelt werden müssen, jedoch keine unmittelbare Lebensgefahr besteht.',
1199:'Erkrankungen ohne Lebensgefahr oder Schäden ohne unmittelbare Gefahr (z. B. technische Störung ohne Manövrierunfähigkeit) werden mit PAN PAN angekündigt.',
1200:'Nicht lebensbedrohliche Verletzungen mit Bedarf an baldiger ärztlicher Versorgung sind ein Dringlichkeitsfall (PAN PAN) – kein Notfall (MAYDAY).',
1201:'Ein Maschinenschaden, der die Sicherheit des Schiffsverkehrs gefährden könnte (z. B. drohende Manövrierunfähigkeit in enger Fahrrinne), ist ein Dringlichkeitsfall (PAN PAN).',
1202:'Das Sicherheitszeichen lautet SECURITE (frz. Aussprache, dreimal gesprochen). Es kündigt wichtige nautische Warnungen oder Wetterwarnungen an.',
1203:'Mit SECURITE werden wichtige nautische Warnmeldungen (z. B. Treibgut, Nebel, Pegelstand) oder wichtige Wetterwarnungen angekündigt – kein medizinischer Bezug.',
1204:'Ein treibender Baumstamm ist eine Gefahr für die Schifffahrt – daher ist eine Sicherheitsmeldung (SECURITE) zu verbreiten.',
1205:'Eine vertriebene Tonne ist eine falsch positionierte Schifffahrtsmarkierung und damit eine Gefahr – daher ist eine Sicherheitsmeldung (SECURITE) zu verbreiten.',
1206:'Der Schiffsführer trägt die Gesamtverantwortung für das Schiff und entscheidet daher über die Art der auszusendenden Sprechfunkmeldung.',
};

// ── SRC I: Grundlagen ─────────────────────────────────────────────────────
1:'Mobiler Seefunkdienst verbindet Küsten- und Seefunkstellen miteinander – nicht nur Schiffe untereinander und nicht nur tragbare Geräte.',
2:'Das GMDSS ermöglicht schnelle und genaue Alarmierung in Seenotfällen und sichert dadurch die Schifffahrt weltweit.',
3:'Das GMDSS wurde für Not-, Dringlichkeits- und Sicherheitsfälle eingeführt – alle drei Kategorien, nicht nur Notfälle.',
4:'Die ITU (Internationale Fernmeldeunion) legt die grundlegenden Regelungen für die internationale Telekommunikation fest – keine operative Aufsicht und kein Abrechnungsdienst.',
5:'Die VO Funk (Radio Regulations) regelt Frequenzzuweisungen und Betriebsverfahren im Seefunkdienst – nicht Schiffsausrüstung oder Radarnutzung.',
6:'Das BSH gibt „Funkdienst für die Klein- und Sportschifffahrt" heraus – die maßgebliche Publikation für Sportseefunker in Deutschland.',
7:'Eine Küstenfunkstelle ist eine ortsfeste (landseitige) Funkstelle des mobilen Seefunkdienstes – nicht an Bord eines Schiffes.',
8:'Öffentlicher Funkverkehr dient der Allgemeinheit zum Nachrichtenaustausch über öffentliche Netze – er unterliegt dem Fernmeldegeheimnis.',
9:'Für öffentlichen Funkverkehr braucht man zusätzlich einen Vertrag mit einer Abrechnungsgesellschaft – das Seefunkzeugnis und die Ship Station Licence sind für alle Seefunkstellen nötig.',
10:'Wenn Nachrichten bei einer Küstenfunkstelle vorliegen, erhält die Seefunkstelle eine individuelle Benachrichtigung oder erfährt es durch Abhören von Sammelanrufen.',
11:'Seefunkgespräche werden nach Gesprächsdauer und Preis der Verrechnungseinheiten abgerechnet – keine Entfernungsgebühren.',
12:'Eine „Sea-Area" im GMDSS ist ein festgelegtes Seegebiet (A1–A4), das die erforderliche Funkausrüstung vorschreibt.',
13:'Die GMDSS-Seegebiete heißen A1, A2, A3 und A4 – internationale Bezeichnungen, keine NAVAREA-Einteilung.',
14:'Seegebiet A1 ist die Zone, die von einer UKW-Küstenfunkstelle mit kontinuierlichem DSC-Wachdienst abgedeckt wird.',
15:'COSPAS-SARSAT und Inmarsat sind die satellitengestützten Alarmierungssysteme im GMDSS – EPIRB ist ein Gerät, das diese Systeme nutzt.',
16:'MSI (Maritime Safety Information) sind Nachrichten für die Sicherheit der Seeschifffahrt – Wetterwarnungen, Navigationswarnungen usw.',
17:'„WX" ist das Kürzel für Weather (Wetter) – Wetterbericht.',
18:'„NX" steht für Navigational (Warning) – nautische Warnnachricht.',
19:'AIS ist das Automatische Schiffsidentifizierungssystem, das statische und dynamische Schiffsdaten auf UKW überträgt – nicht das ATIS-System des Binnenfunks.',
20:'ETA = Estimated Time of Arrival = voraussichtliche Ankunftszeit.',
21:'Im Seefunkdienst gilt die koordinierte Weltzeit UTC – keine Orts- oder Sommerzeit.',
22:'LT = Local Time = Ortszeit des Schiffsstandortes – kann von UTC abweichen.',
23:'Ein funkärztliches Beratungsgespräch heißt Medico-Gespräch und wird über Küstenfunkstellen abgewickelt.',
// ── SRC II: Funkausrüstung & Zulassung ───────────────────────────────────
24:'Eine Seefunkstelle ist eine mobile Funkstelle des Seefunkdienstes an Bord eines nicht dauernd verankerten Seefahrzeuges.',
25:'Der Fahrzeugführer muss ein Zeugnis besitzen, das zum Bedienen der eingebauten Anlage berechtigt – bei UKW-Anlage das SRC, bei GW/KW zusätzlich das LRC.',
26:'Das SRC berechtigt zum Bedienen von UKW-Funkanlagen auf nicht funkausrüstungspflichtigen Fahrzeugen und Traditionsschiffen.',
27:'Gewerbsmäßig genutzte Sportboote ab 12 m Länge müssen mit einer UKW-Seefunkanlage ausgerüstet sein.',
28:'Für den Betrieb einer Seefunkstelle benötigt man Ship Station Licence, zugelassenes Gerät und ausreichendes Seefunkzeugnis des Fahrzeugführers.',
29:'Bei Überprüfung müssen Ship Station Licence und das Seefunkzeugnis des Fahrzeugführers vorgelegt werden.',
30:'In Deutschland stellt die Bundesnetzagentur (BNetzA), Außenstelle Hamburg, die Zuteilungsurkunde für Seefunkstellen aus.',
31:'Die Zuteilungsurkunde (Ship Station Licence) muss im Original an Bord mitgeführt werden – keine Kopie.',
32:'Namensänderungen müssen der Bundesnetzagentur schriftlich gemeldet werden, damit die Zuteilungsurkunde aktualisiert wird.',
33:'Beim Austausch der Funkanlage muss die Bundesnetzagentur schriftlich informiert werden.',
34:'Ein UKW-Seefunkgerät muss für den Seefunkdienst zugelassen oder CE-konform in Verkehr gebracht worden sein – kein TÜV-Prüfzeichen nötig.',
35:'Funksicherheitszeugnisse für gewerbsmäßig genutzte Sportboote werden von der Dienststelle Schiffssicherheit der BG Verkehr ausgestellt.',
36:'Ein Funksicherheitszeugnis ist nur bei gewerbsmäßiger Nutzung eines Sportbootes ab 12 m erforderlich.',
37:'Fest installierte UKW-Seefunkanlagen können auf 1 Watt oder maximal 25 Watt umgeschaltet werden.',
38:'Sechsstellige Rufzeichen für Seefunkstellen vergibt die Bundesnetzagentur (BNetzA), Außenstelle Hamburg.',
39:'Bundesnetzagentur (BNetzA) und BSH sind beide berechtigt, die Funktionsfähigkeit von Seefunkstellen zu überprüfen.',
40:'Das mindestens vierstellige Unterscheidungssignal für im Seeschiffsregister eingetragene Yachten teilt das zuständige Amtsgericht zu.',
41:'Rufzeichen wie „DDTW" mit vier Buchstaben kennzeichnen Seefunkstellen an Bord in einem deutschen Seeschiffsregister eingetragener Schiffe.',
42:'Abhörverbot und Fernmeldegeheimnis sind im Telekommunikationsgesetz (TKG) geregelt.',
43:'Zur Wahrung des Fernmeldegeheimnisses verpflichtet sind alle Personen, die eine Seefunkstelle beaufsichtigen, bedienen oder Kenntnis vom Nachrichtenaustausch erlangt haben.',
44:'Nur Aussendungen „An alle Funkstellen" dürfen uneingeschränkt aufgenommen und weitergegeben werden.',
45:'Ordnungsgemäß in Verkehr gebrachte Funkgeräte tragen das CE-Zeichen.',
46:'Zur Teilnahme am Binnenschifffahrtsfunk muss eine spezielle Kombi-Anlage oder eine zusätzliche Anlage für den Binnenschifffahrtsfunk vorhanden sein – eine normale Seefunkanlage reicht nicht.',
47:'Kapazität (60 Ah) ÷ Stromaufnahme (0,5 A) = 120 Stunden Betriebsdauer.',
48:'Im Sendebetrieb nimmt das Funkgerät deutlich mehr Strom auf als im Empfangsbetrieb – die Batterie wird schneller entladen und die Betriebsdauer verkürzt sich.',
49:'Im Empfangsbetrieb nehmen UKW-Seefunkanlagen je nach Gerät zwischen 0,3 und 1 Ampere auf.',
50:'Im Sendebetrieb bei 25 Watt liegt die typische Stromaufnahme zwischen 4 und 8 Ampere.',
51:'Die Rauschsperre (Squelch) aktiviert den Lautsprecher erst bei ausreichendem Empfangssignalpegel – Rauschen wird unterdrückt.',
52:'GPS bestimmt die genaue Position und liefert die genaue Zeit – beides für GMDSS-Funkanlagen wichtig (automatische Positionsübermittlung beim DSC-Notalarm).',
// ── SRC III: DSC ─────────────────────────────────────────────────────────
53:'DSC = Digitaler Selektivruf (Digital Selective Calling) – ein digitales Rufverfahren im Seefunkdienst.',
54:'Ein DSC ist eine digitale Aussendung, die bei der gerufenen Funkstelle ein optisches und/oder akustisches Signal auslöst – vergleichbar mit einem digitalen Klingelzeichen.',
55:'DSC ermöglicht die Verkehrsaufnahme sowohl in Richtung Schiff–Küstenfunkstelle als auch Schiff–Schiff.',
56:'DSC-Signale haben eine deutlich größere Reichweite als analoge Sprachaussendungen im gleichen Frequenzbereich.',
57:'Für DSC-Ankündigung einer Dringlichkeitsmeldung auf UKW wird Kanal 70 benutzt.',
58:'DSC-Alarmierungen auf UKW erfolgen ausschließlich auf Kanal 70.',
59:'Eine DSC-ausgerüstete Seefunkstelle wird durch Schiffsname, Rufzeichen und MMSI gekennzeichnet.',
60:'Empfangene DSC-Notalarme werden automatisch gespeichert – damit gehen keine Informationen verloren.',
61:'MMSI = Maritime Mobile Service Identity = die Rufnummer im Seefunkdienst.',
62:'Die Seefunkkennzahlen (MID) für Deutschland sind 211 und 218.',
63:'Die eigene MMSI steht in der Zuteilungsurkunde (Ship Station Licence).',
64:'Die MMSI besteht aus neun Ziffern, wobei die ersten drei die Seefunkkennzahl (MID) des Landes enthalten.',
65:'Die Küstenfunkstellen-MMSI beginnt mit zwei Nullen, gefolgt von der dreistelligen MID und vier weiteren Ziffern.',
66:'Die Ziffernfolge 002111240 beginnt mit 00 → Küstenfunkstelle, 211 → Deutschland → deutsche Küstenfunkstelle.',
67:'Die Nationalität einer Seefunkstelle ist an den ersten drei Ziffern der MMSI erkennbar – der Seefunkkennzahl (MID).',
68:'Nur ein angeschlossener GPS-Empfänger stellt sicher, dass beim DSC-Notalarm automatisch die aktuelle Position übermittelt wird.',
// ── SRC IV: Technik & Frequenzen ─────────────────────────────────────────
69:'30–300 MHz ist der Bereich der Ultrakurzwellen (UKW / VHF = Very High Frequency).',
70:'Das SRC (Short Range Certificate / Beschränkt Gültiges Funkbetriebszeugnis) ist das Mindestzeugnis für GMDSS auf UKW.',
71:'Das SRC berechtigt zum mobilen Seefunkdienst auf UKW/VHF – nicht auf GW/KW und nicht für Satellit.',
72:'Duplex = Gegensprechen auf zwei Frequenzen – beide Seiten können gleichzeitig senden und empfangen.',
73:'Simplex = Wechselsprechen auf einer Frequenz – immer nur einer sendet.',
74:'Semi-Duplex = Wechselsprechen auf zwei Frequenzen – man drückt die Sprechtaste zum Senden, nutzt aber einen Duplex-Kanal.',
75:'Die UKW-Kanäle 06, 08, 72 und 77 sind international ausschließlich für Schiff-Schiff-Verkehr vorgesehen.',
76:'Die UKW-Kanäle 75 und 76 dürfen ausschließlich für navigationsrelevanten Funkverkehr genutzt werden.',
77:'Atmosphärische Störungen sind im VHF-Bereich kein relevantes Problem – anders als auf Mittelwelle oder Kurzwelle.',
78:'UKW-Wellen breiten sich geradlinig (quasioptisch) aus – sie folgen der Sichtlinie und werden nicht an der Ionosphäre reflektiert.',
79:'Die internationalen UKW-Seefunkkanäle reichen von Kanal 1 bis 28 und 60 bis 88.',
80:'Die Reichweite einer UKW-Anlage hängt hauptsächlich von der Antennenhöhe ab – je höher, desto weiter der Horizont.',
81:'UKW-Antennen müssen vertikal ausgerichtet sein, da die Funkwellen vertikal polarisiert sind.',
82:'Metallische Gegenstände in der Nähe der Antenne beeinträchtigen die Abstrahlung am stärksten.',
83:'Schlechtes Wetter hat keinen Einfluss auf die Reichweite eines UKW-Handsprechfunkgerätes – im Gegensatz zu Antennenhöhe, Akkuladung und Sendeleistung.',
84:'Ob das Senden in ausländischen Häfen gestattet ist, hängt von den Vorschriften des jeweiligen Landes ab.',
// ── SRC V: Betriebsverfahren ──────────────────────────────────────────────
85:'Rangfolge im Seefunkdienst: 1. Not, 2. Dringlichkeit, 3. Sicherheit, 4. Routine.',
86:'Im Schiffstagebuch sind Not-, Dringlichkeits- und Sicherheitsverkehr sowie wichtige Vorkommnisse zu dokumentieren.',
87:'Funkverkehr zwischen Küstenfunkstellen des Revier-/Hafenfunkdienstes und Seefunkstellen ist nichtöffentlicher Funkverkehr.',
88:'Der Revier- und Hafenfunkdienst übermittelt Nachrichten, die ausschließlich das Führen, die Fahrt und Sicherheit von Schiffen auf dem Revier oder in Häfen betreffen.',
89:'Der Schiffslenkungsfunkdienst ist neben dem Revier- und Hafenfunkdienst der zweite Sicherheitsfunkdienst im mobilen Seefunkdienst.',
90:'Bei einer Verbindung zwischen See- und Küstenfunkstelle bestimmt die Küstenfunkstelle den Arbeitskanal.',
91:'Küstenfunkstellen des Revier- und Hafenfunkdienstes werden nach dem Muster „Geografischer Name + Art des Dienstes + Radio" bezeichnet, z. B. „Warnemünde Traffic".',
92:'„Warnemünde Traffic" ist der Rufname der Küstenfunkstelle des Revierfunkdienstes in Warnemünde.',
93:'Das Dringlichkeitszeichen zeigt an, dass eine sehr dringende Meldung folgt, welche die Sicherheit einer mobilen Einheit oder Person betrifft – jedoch keine unmittelbare Lebensgefahr.',
94:'Das Dringlichkeitszeichen im Sprechfunk lautet PAN PAN (dreimal gesprochen).',
95:'PAN PAN kündigt eine Dringlichkeitsmeldung an.',
96:'Eine Dringlichkeitsmeldung auf UKW wird per DSC auf Kanal 70 angekündigt und dann per Sprechfunk auf Kanal 16 ausgesendet.',
97:'„URGENCY" im DSC-Controller zeigt an, dass die folgende Meldung dringend ist und die Sicherheit einer mobilen Einheit oder Person betrifft.',
98:'Dringlichkeitsmeldungen können an alle Funkstellen oder an eine bestimmte Funkstelle gerichtet werden.',
99:'Eine an alle Funkstellen gesendete Dringlichkeitsmeldung muss durch eine Meldung an alle Funkstellen aufgehoben werden.',
100:'Das Sicherheitszeichen im Seefunkdienst lautet SECURITE (dreimal gesprochen).',
101:'Mit SECURITE wird eine Sicherheitsmeldung eingeleitet.',
102:'Eine Sicherheitsmeldung enthält eine wichtige nautische Warnnachricht oder eine wichtige Wetterwarnung.',
103:'Sportfahrzeuge benutzen in deutschen Hoheitsgewässern vorzugsweise Kanal 69 oder 72 für den Schiff-Schiff-Verkehr.',
104:'UKW-Handsprechfunkgeräte werden vorzugsweise für Funkverkehr an Bord und für die Verbindung mit Überlebensfahrzeugen eingesetzt.',
105:'Testsendungen dürfen 10 Sekunden nicht überschreiten und müssen das Wort „Test" sowie eine Schiffskennung enthalten.',
106:'Der Schiff-Schiff-Verkehr auf UKW erfolgt im Wechselsprechen (Simplex) auf einer Frequenz.',
107:'Kanal 70 ist ausschließlich für den Digitalen Selektivruf (DSC) reserviert – keine Sprachaussendungen.',
108:'Kanal 16 dient für Not-, Dringlichkeitsverkehr, Ankündigung von Sicherheitsmeldungen und als allgemeiner Anrufkanal.',
109:'Mit GMDSS-Seefunkanlage muss auf Kanal 70 (DSC-Wachkanal) empfangsbereit sein – nicht auf Kanal 16.',
110:'Ohne GMDSS-Anlage (reine Sprechfunkanlage) muss auf Kanal 16 abgehört werden.',
111:'Kanal 06 ist der bevorzugte Kanal für Schiff-Schiff-Verkehr und koordinierte SAR-Einsätze.',
112:'Anrufkanal dient der Verbindungsaufnahme, Arbeitskanal der eigentlichen Abwicklung des Funkverkehrs.',
113:'Küstenfunkstellen mit DSC werden auf Kanal 70 oder dem veröffentlichten Arbeitskanal gerufen – nicht auf Kanal 16.',
114:'Küstenfunkstellen ohne DSC werden direkt auf dem Arbeitskanal gerufen.',
115:'Vor dem Anruf auf einem Arbeitskanal muss geprüft werden, ob laufender Funkverkehr gestört werden würde.',
// ── SRC VI: NAVTEX ───────────────────────────────────────────────────────
116:'NAVTEX = Nautische Warnnachrichten im Funktelexverfahren (Navigational Telex) auf Mittelwelle.',
117:'NAVTEX ist der terrestrische Dienst zur Verbreitung von MSI (Maritime Safety Information).',
118:'Auf 518 kHz (englisch) und 490 kHz (Landessprache) bieten DWD und BSH gemeinsam den deutschen NAVTEX-Dienst an.',
119:'NAVTEX-Meldungen können auf ca. 600 Seemeilen vom Sender empfangen werden.',
120:'Beim NAVTEX-Empfänger müssen die gewünschten Sender und die Art der benötigten Meldungen eingestellt werden.',
121:'Navigationswarnungen, meteorologische Warnungen und SAR-Meldungen können im NAVTEX nicht unterdrückt werden – sie sind sicherheitsrelevant.',
122:'Auf 490 kHz werden NAVTEX-Nachrichten in der Landessprache der Sendestelle ausgestrahlt.',
123:'Deutsche NAVTEX-Sender senden alle 4 Stunden reguläre Informationen aus.',
124:'Eine NAVAREA ist ein international festgelegtes Vorhersage- und Seewarngebiet – eines von 21 NAVAREA-Gebieten weltweit.',
// ── SRC VII: Not- und Sicherheitsverkehr ─────────────────────────────────
125:'SAR = Search and Rescue = Suche und Rettung.',
126:'Ein RCC (Rescue Co-ordination Centre) koordiniert die im Seenotfall zur Verfügung stehenden Kräfte und den Notverkehr.',
127:'Ein MRCC (Maritime Rescue Co-ordination Centre) koordiniert alle SAR-Maßnahmen auf See.',
128:'„On-Scene Communication" ist der Funkverkehr vor Ort im Seenotfall zwischen Havarist und Helfern.',
129:'Der On-Scene Coordinator (OSC) leitet die Such- und Rettungsmaßnahmen direkt vor Ort.',
130:'Funkverkehr vor Ort ist der Funkverkehr zwischen dem Schiff in Not, den helfenden Fahrzeugen und dem koordinierenden Fahrzeug.',
131:'Nur der Fahrzeugführer ist berechtigt, das Aussenden einer Notmeldung zu veranlassen.',
132:'Mit DSC ausgerüstete Schiffe müssen auf Kanal 70 empfangsbereit sein – der DSC-Wachkanal im GMDSS.',
133:'Das Notzeichen im Sprechfunk lautet MAYDAY (dreimal gesprochen, von frz. „m\'aidez" = helft mir).',
134:'Der Notverkehr im Sprechfunk wird mit MAYDAY eingeleitet – nicht mit dem Schiffsnamen oder SOS.',
135:'Ein Seenotfall liegt vor, wenn ein Schiff oder eine Person von einer ernsten und unmittelbaren Gefahr bedroht ist und sofortige Hilfe benötigt.',
136:'Bei Lebensgefahr wird die Alarmierungspriorität „Notfall" gewählt.',
137:'Im Notfall darf jede verfügbare und geeignete Frequenz genutzt werden – nicht nur die Notfrequenzen.',
138:'Notverkehr findet vorzugsweise auf Kanal 16 statt.',
139:'Auf Kanal 16 dürfen Notmeldungen, Dringlichkeitsmeldungen und Ankündigungen von Sicherheitsmeldungen übermittelt werden.',
140:'Die Einleitung des Notverkehrs wird wiederholt, wenn keine Antwort erfolgt oder der Fahrzeugführer es für notwendig hält.',
141:'Den Notalarm für ein anderes Schiff richtet man grundsätzlich an die nächstgelegene Küstenfunkstelle oder an alle Funkstellen.',
142:'Eine Seefunkstelle bestätigt einen DSC-Notalarm nur, wenn sie tatsächlich Hilfe leisten kann.',
143:'Die Bestätigung darf erst nach Bestätigung durch eine Küstenfunkstelle oder nach angemessener Wartefrist erfolgen, um zu vermeiden, dass alle gleichzeitig antworten.',
144:'Ein auf Kanal 70 empfangener Notalarm wird auf Kanal 16 im Sprechfunkverfahren bestätigt.',
145:'SILENCE MAYDAY fordert alle nicht am Notverkehr beteiligten Funkstellen zur Funkstille auf.',
146:'SILENCE MAYDAY wird von der Funkstelle ausgesendet, die den Notverkehr leitet.',
147:'Nach Eingang eines Notalarms übernimmt das MRCC die Koordinierung und Information zu den SAR-Maßnahmen.',
148:'Bremen Rescue Radio ist auf Kanal 16 (Sprechfunk) und Kanal 70 (DSC) empfangsbereit.',
149:'Im Notfall mit SAR-Hubschraubern gilt das Betriebsverfahren des mobilen Seefunkdienstes.',
150:'Das Handbuch „Suche und Rettung" enthält internationale Redewendungen, Abkürzungen und Verfahren für Notfälle.',
151:'SAR-Einheiten arbeiten im UKW-Bereich – auf Kanal 16 und Kanal 06.',
152:'Im Funkverkehr zwischen Seefunkstellen und SAR-Hubschraubern gilt das Betriebsverfahren des Seefunkdienstes.',
153:'Für den Funkverkehr mit SAR-Hubschraubern werden vorzugsweise Kanal 16 und Kanal 06 benutzt.',
154:'Bei SAR-Hubschraubereinsätzen werden Kanal 16 und 06 durch Zweikanal-Überwachung (Dual Watch) gleichzeitig überwacht.',
155:'Ein Schiff in Not soll Kanal 16 abhören, bis der SAR-Hubschrauber ankommt.',
156:'Während eines Notverkehrs auf Kanal 16 darf eine Dringlichkeitsmeldung per DSC auf Kanal 70 angekündigt und dann auf einem Schiff-Schiff-Kanal ausgesendet werden.',
157:'Bei irrtümlichem Notalarm: Gerät zurücksetzen, Fehlalarm per DSC zurücknehmen und per Sprechfunk auf Kanal 16 „An alle Funkstellen" zurücknehmen.',
158:'Ein UKW-Empfänger (ohne Senderfunktion) kann keine SAR-Maßnahmen auslösen oder erleichtern – er kann nur empfangen.',
159:'SART und EPIRB werden zur Ortsbestimmung eingesetzt: SART via Radar, EPIRB via Satellit (COSPAS-SARSAT).',
160:'Eine EPIRB soll im äußeren Decksbereich installiert werden, damit sie bei einem Untergang des Schiffes automatisch aufschwimmt und auslöst.',
161:'Eine EPIRB darf nur im echten Notfall aktiviert werden – Testsendungen über das Satellitensystem sind nicht zulässig.',
162:'Eine EPIRB kann im Notfall manuell oder automatisch (durch Wasserdruckauslöser) aktiviert werden.',
163:'EPIRBs werden im Seenotfall automatisch durch den Wasserdruckauslöser aktiviert, wenn sie ins Wasser eintauchen.',
164:'Eine EPIRB sendet Notsignal, Identifikationsmerkmal und – wenn GPS vorhanden – die Position.',
165:'In den Seegebieten A1–A3 läuft der EPIRB-Alarm dank geostationärer Satelliten innerhalb weniger Minuten im MRCC auf.',
166:'Ohne GPS-Positionsdaten kann es bei COSPAS-SARSAT (LEOSAR) bis zu 4 Stunden dauern, bis die Position ermittelt ist.',
167:'Die Positionsermittlung dauert länger, wenn keine GPS-Daten vorhanden sind, weil Überflüge der umlaufenden LEOSAR-Satelliten abgewartet werden müssen.',
168:'Die maximale Positionsabweichung einer COSPAS-SARSAT-EPIRB ohne GPS beträgt 2 Seemeilen.',
169:'121,5 MHz dient zur Zielfahrt (Homing) für SAR-Kräfte vor Ort, 406 MHz zur Alarmierung und Positionsbestimmung über Satelliten.',
170:'An einer EPIRB müssen Schiffsname/Rufzeichen/MMSI, Seriennummer, Batteriehaltbarkeitsdatum und Datum des Wasserdruckauslösers erkennbar sein.',
171:'Vor der Wartung muss sichergestellt sein, dass kein Fehlalarm ausgelöst wird, wenn die EPIRB aus der Halterung entfernt wird.',
172:'An der EPIRB sind regelmäßig Batteriehaltbarkeitsdatum, Haltbarkeitsdatum des Wasserdruckauslösers und die Funktion entsprechend Herstellerangaben zu prüfen.',
173:'Ein aktivierter SART erscheint auf dem Radarbildschirm als Linie von mindestens zwölf Punkten/Zeichen.',
174:'Das SART-Signal wird von einem Radargerät empfangen und angezeigt – kein GPS oder DSC.',
175:'Eine UKW-Seefunkanlage alarmiert alle in Funkreichweite befindlichen Seefunkstellen gleichzeitig – ein Mobiltelefon kann nur einzelne Nummern anrufen.',
176:'Die UKW-Seefunkanlage erreicht alle in Funkreichweite befindlichen Fahrzeuge gleichzeitig – das Mobiltelefon kann nur einen Gesprächspartner erreichen.',
177:'Telefongespräche sind Einzelverbindungen – andere Fahrzeuge können nicht mithören, sodass wichtige Rettungsinformationen nicht allen Beteiligten zur Verfügung stehen.',
178:'Der Notverkehr wird mit einer Meldung beendet, die mit SILENCE FINI abschließt.',
179:'Ein SART sendet Ortungsfunksignale, die von Radargeräten auf einem Schirm als Linie von Punkten dargestellt werden.',
180:'Eine EPIRB alarmiert und kennzeichnet die Notposition über das COSPAS-SARSAT-Satellitensystem.',

// ── LRC I: Satellitenfunk Grundlagen ─────────────────────────────────────
1001:'Im Satellitenfunk heißt die mobile Schiffsanlage Mobile Earth Station (MES) – also Schiffs-Erdfunkstelle.',
1002:'Eine Schiffs-Erdfunkstelle ist die mobile Erdfunkstelle des Satelliten-Seefunkdienstes an Bord eines Schiffes.',
1003:'Eine Land-Erdfunkstelle (LES = Land Earth Station) ist die ortsfeste landseitige Gegenstelle im Satellitenfunknetz.',
1004:'Der Azimutwinkel ist der horizontale Winkel vom Meridian des Schiffes zum Satelliten – die „Kompesspeilung" des Satelliten.',
1005:'Der Elevationswinkel (elevation angle) ist der Winkel zwischen Horizont und Satellit vom Schiff aus – gibt an, wie hoch der Satellit am Himmel steht.',
1006:'Die ITU-Region 1 umfasst Europa und Afrika.',
1007:'A3 ist das Seegebiet innerhalb der Überdeckung eines geostationären Inmarsat-Satelliten mit ununterbrochener DSC-Alarmierungsbereitschaft.',
1008:'A4 umfasst die Polgebiete – Gewässer nördlich von ca. 70° Nord und südlich von ca. 70° Süd – die von geostationären Satelliten nicht abgedeckt werden.',
1009:'Inmarsat-Satelliten sind geostationär und können die Polgebiete (A4) nicht abdecken – nur polumlaufende Satelliten (COSPAS-SARSAT) erreichen diese Gebiete.',
1010:'AMVER (Automated Mutual-Assistance Vessel Rescue System) ist das Positionsmeldesystem für Such- und Rettungszwecke.',
1011:'AIS arbeitet im UKW-Bereich (VHF) auf den Kanälen 87B und 88B (161,975 MHz und 162,025 MHz).',
1012:'Die NAVTEX-Kurzwellenfrequenz ist 4209,5 kHz.',
1013:'Im Seenotfall kann ein Alarm über Satelliten über die Schiffs-Erdfunkstelle (SES) oder eine Satelliten-Seenotfunkbake (EPIRB) ausgelöst werden.',
1014:'COSPAS-SARSAT nutzt sowohl polumlaufende (LEOSAR) als auch geostationäre (GEOSAR) Satelliten – Inmarsat ist rein geostationär.',
// ── LRC II: LRC-Zeugnis ───────────────────────────────────────────────────
1015:'Im Seegebiet A3 (Inmarsat-Abdeckung) ist das LRC (Long Range Certificate / Allgemeines Funkbetriebszeugnis) das Mindestzeugnis.',
1016:'Das LRC berechtigt zum mobilen Seefunkdienst und zum mobilen Seefunkdienst über Satelliten.',
1017:'Mit dem LRC dürfen Seefunkanlagen im UKW-, GW- und KW-Bereich sowie über Satellit auf Sportfahrzeugen und Traditionsschiffen bedient werden.',
1018:'Für den Betrieb einer KW/GW-DSC-Anlage ist das LRC (Allgemeines Funkbetriebszeugnis) erforderlich.',
// ── LRC III: GW- und KW-Frequenzen ───────────────────────────────────────
1019:'2177 kHz ist die nationale und internationale Routineanruffrequenz für Schiff-Schiff-DSC auf Grenzwelle.',
1020:'2177,0 kHz ist die Antwortfrequenz der Küstenfunkstelle auf Routineanrufe per DSC.',
1021:'2189,5 kHz ist die internationale DSC-Anruffrequenz für Routineanrufe an Küstenfunkstellen auf Grenzwelle.',
1022:'Für DSC im Kurzwellenbereich werden die Frequenzbereiche 4, 6, 8, 12 und 16 MHz genutzt.',
1023:'Die Bestätigung eines auf 2187,5 kHz (DSC-Notruffrequenz GW) empfangenen Notalarms erfolgt auf 2182,0 kHz im Sprechfunkverfahren.',
1024:'Im KW-Bereich gewährleistet ein Wachempfänger im Scan-Betrieb die Empfangsbereitschaft auf mehreren Frequenzen gleichzeitig.',
// ── LRC IV: Wellenausbreitung ────────────────────────────────────────────
1025:'Grenzwelle (GW/MF) umfasst 1605–4000 kHz.',
1026:'SSB mit unterdrücktem Träger wird als J3E bezeichnet – die effizienteste Sendeart für Weitverkehr.',
1027:'Grenzwelle (GW/MF) reicht für mindestens 150 Seemeilen Reichweite bei Tagbetrieb aus – UKW nicht.',
1028:'Im LW- und tagsüber im MW/GW-Bereich spielt die Bodenwelle die entscheidende Rolle bei der Ausbreitung.',
1029:'Im Seegebiet A2 (ca. 150 sm von der Küste) sind GW für die Küstenfunkstelle und UKW für nahe Seefunkstellen geeignet.',
1030:'Gewitter verursachen auf Mittelwelle (NAVTEX 518/490 kHz) starke atmosphärische Störungen bis zur vollständigen Unlesbarkeit.',
1031:'Kurzwelle (KW/HF) wird für den Weitverkehr im terrestrischen Seefunkdienst genutzt – Raumwellenausbreitung über weite Strecken.',
1032:'Kurzwelle (KW/HF) umfasst den allgemeinen Bereich von 3–30 MHz.',
1033:'Im Kurzwellenbereich (KW/HF) spielt die Raumwelle die entscheidende Rolle – sie wird an der Ionosphäre reflektiert.',
1034:'Die „Tote Zone" (Skip Zone) tritt im Kurzwellenbereich auf – zwischen dem Ende der Bodenwelle und dem ersten Raumwelleneinfall gibt es keinen Empfang.',
1035:'Gegen Mitternacht ist die Ionosphäre stärker ionisiert – für die gleiche Entfernung wird ein niedrigerer Frequenzbereich benötigt.',
1036:'Kurzwellenverbindungen sind durch tageszeitliche, jahreszeitliche und solare Schwankungen der Ionosphäre nicht zuverlässig vorherzuplanen.',
1037:'Für Weitverkehr auf KW sollte die Antenne die Energie möglichst flach abstrahlen, damit die Raumwelle mit wenigen Ionosphärensprüngen den Zielort erreicht.',
1038:'Für die Strecke Mittelmeer nach Norddeutschland ist tagsüber der 8-MHz-Bereich (Kurzwelle) typischerweise am besten geeignet.',
1039:'In den Abendstunden ist für die Verbindung Karibik–USA der 6-MHz-Bereich auf Kurzwelle oft am geeignetsten, da die Ionosphäre sich nach Sonnenuntergang abschwächt.',
1040:'Auf 100 sm Entfernung ist Grenzwelle (GW/MF) die geeignetste Option – sie überbrückt zuverlässig kurze bis mittlere Entfernungen.',
// ── LRC V: GW/KW-Betriebsverfahren ───────────────────────────────────────
1041:'Bei Verbindungen zwischen See- und Küstenfunkstelle bestimmt die Küstenfunkstelle die zu benutzende Arbeitsfrequenz.',
1042:'Das „Verzeichnis der Küstenfunkstellen" (List of Coast Stations) der ITU enthält Angaben zu Arbeitsfrequenzen von Küstenfunkstellen.',
1043:'In deutschen Häfen dürfen UKW (VHF), UHF und der 1,6-GHz-Bereich (Inmarsat) genutzt werden – KW/GW sind in Häfen verboten.',
1044:'„ITU-Channel 1604" bedeutet Kanal 04 im 16-MHz-Seefunkband – die erste Zahl ist das Frequenzband in MHz.',
1045:'2182,0 kHz ist die internationale Not- und Sicherheitsfrequenz für Sprechfunk auf Grenzwelle.',
1046:'Für die Dringlichkeitsmeldung „An alle Funkstellen" auf GW wird nach DSC-Ankündigung auf 2187,5 kHz der Sprechfunk auf 2182,0 kHz verwendet.',
1047:'Während eines Notverkehrs auf 2182 kHz wird eine Dringlichkeitsmeldung zunächst per DSC auf 2187,5 kHz angekündigt und dann auf einer Schiff-Schiff-Frequenz ausgesendet.',
1048:'Eine Sicherheitsmeldung auf GW wird per DSC auf 2187,5 kHz angekündigt und dann per Sprechfunk auf einer GW-Schiff-Schiff-Arbeitsfrequenz ausgesendet.',
1049:'Notverkehr im KW-Sprechfunkverfahren wird auf der Sprechfunk-Notfrequenz des KW-Bandes abgewickelt, in dem der Notalarm ausgesendet wurde.',
1050:'Im GW- und KW-Bereich wird für Sprachaussendungen Einseitenband mit unterdrücktem Träger (SSB, J3E) verwendet – energieeffizienter als AM.',
// ── LRC VI: Inmarsat ──────────────────────────────────────────────────────
1051:'Das Inmarsat-Handbuch enthält Angaben über die Abdeckungsbereiche der Inmarsat-Satelliten.',
1052:'Das Inmarsat-Handbuch enthält auch Angaben über Land-Erdfunkstellen (LES).',
1053:'Der PSA (Point of Service Activation) schaltet die Schiffs-Erdfunkstelle für den Inmarsat-Dienst frei.',
1054:'Die NCS (Network Co-ordination Station) vergibt automatisch die Arbeitskanäle an LES und MES im Inmarsat-Netz.',
1055:'Inmarsat-Satelliten sind geostationär – sie stehen immer über demselben Punkt des Äquators.',
1056:'Geostationäre Satelliten befinden sich über 0° Breite (Äquator) in etwa 35.786 km Höhe.',
1057:'AOR-E = Atlantic Ocean Region East – deckt den östlichen Atlantik einschließlich Europa ab.',
1058:'IOR = Indian Ocean Region – deckt den Indischen Ozean ab.',
1059:'POR = Pacific Ocean Region – deckt den Pazifischen Ozean ab.',
1060:'Von Hawaii aus ist der POR-Satellit (Pazifik) am besten erreichbar für eine Verbindung nach Europa.',
1061:'Von den Malediven (Indischer Ozean) bietet der IOR-Satellit die beste Verbindung nach Europa.',
1062:'Seegebiet A4 (Polargebiete) liegt außerhalb der Abdeckung geostationärer Inmarsat-Satelliten.',
1063:'Seegebiet A2 ist das Gebiet innerhalb der Sprechfunkreichweite einer GW-Küstenfunkstelle mit ununterbrochener DSC-Bereitschaft.',
1064:'Die Vorwahl +870 wird für Verbindungen zu Inmarsat-Terminals (Schiffs-Erdfunkstellen) verwendet.',
1065:'Inmarsat-C-Rufnummern beginnen mit der Ziffer 4.',
1066:'Rufnummern, die mit 4 beginnen, gehören zu Inmarsat C.',
1067:'Inmarsat C bietet Telex, Datenübertragung und Telefax in Richtung See–Land – keine Telefonie.',
1068:'Die Funktionsfähigkeit einer Inmarsat-C-Anlage lässt sich prüfen, indem man eine Nachricht von der eigenen an die eigene Anlage schickt (Loopback-Test).',
1069:'Vor dem Ausschalten einer Inmarsat-C-Anlage muss man sich ordnungsgemäß ausloggen, damit das System die Verbindung sauber beendet.',
1070:'Für Anrufe von Land an bestimmte Schiffs-Erdfunkstellen wird der Erweiterte Gruppenanruf (EGC) verwendet.',
1071:'EGC (Enhanced Group Call) wird vom SafetyNet-Dienst für Sicherheitsinformationen über Satelliten genutzt.',
1072:'Über EGC werden maritime Sicherheitsinformationen (MSI) oder Informationen an bestimmte Empfängergruppen ausgesendet.',
1073:'Für den Empfang von EGC-Meldungen wird ein Satelliten-Empfänger (Inmarsat-C-Gerät) benötigt.',
1074:'Über Inmarsat ausgelöste Notalarme werden umgehend an das zuständige RCC oder MRCC weitergeleitet.',
1075:'SafetyNet ist der Inmarsat-Dienst, der maritime Sicherheitsinformationen (MSI) über Satellit verbreitet.',
1076:'SafetyNet verbreitet Maritime Safety Information (MSI) – Navigationswarnungen, Wetterwarnungen usw. – über Satelliten.',
};
